[package]
name = "usbhidusage"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Cry-Tokyo/usbhidusage"
keywords = ["hid", "usb", "usage", "usbhid", "hidusb"]
categories = []
[dependencies]
pcap = "2.2.0"
pnet = "0.35.0"
