#[non_exhaustive]
#[derive(Clone, Copy, PartialEq, PartialOrd, Ord, Eq, Hash, Debug, Default)]
#[repr(u16)]
pub enum AuxiliaryDisplayUsage {
    #[default]
    Undefined,
    AlphanumericDisplay,
    AuxiliaryDisplay,
    Reserved03_1F(u16),
    DisplayAttributesReport = 32,
    ASCIICharacterSet,
    DataReadBack,
    FontReadBack,
    DisplayControlReport,
    ClearDisplay,
    DisplayEnable,
    ScreenSaverDelay,
    ScreenSaverEnable,
    VerticalScroll,
    HorizontalScroll,
    CharacterReport,
    DisplayData,
    DisplayStatus,
    StatNotReady,
    StatReady,
    ErrNotaloadablecharacter,
    ErrFontdatacannotberead,
    CursorPositionReport,
    Row,
    Column,
    Rows,
    Columns,
    CursorPixelPositioning,
    CursorMode,
    CursorEnable,
    CursorBlink,
    FontReport,
    FontData,
    CharacterWidth,
    CharacterHeight,
    CharacterSpacingHorizontal,
    CharacterSpacingVertical,
    UnicodeCharacterSet,
    Font7_Segment,
    _7_SegmentDirectMap,
    Font14_Segment,
    _14_SegmentDirectMap,
    DisplayBrightness,
    DisplayContrast,
    CharacterAttribute,
    AttributeReadback,
    AttributeData,
    CharAttrEnhance,
    CharAttrUnderline,
    CharAttrBlink,
    Reserved4E_7F(u16),
    BitmapSizeX = 128,
    BitmapSizeY,
    MaxBlitSize,
    BitDepthFormat,
    DisplayOrientation,
    PaletteReport,
    PaletteDataSize,
    PaletteDataOffset,
    PaletteData,
    Reserved89(u16),
    BlitReport = 138,
    BlitRectangleX1,
    BlitRectangleY1,
    BlitRectangleX2,
    BlitRectangleY2,
    BlitData,
    SoftButton,
    SoftButtonID,
    SoftButtonSide,
    SoftButtonOffset1,
    SoftButtonOffset2,
    SoftButtonReport,
    Reserved96_C1(u16),
    SoftKeys = 194,
    ReservedC3_CB(u16),
    DisplayDataExtensions = 204,
    ReservedCD_CE(u16),
    CharacterMapping = 207,
    ReservedD0_DC(u16),
    UnicodeEquivalent = 221,
    ReservedDE(u16),
    CharacterPageMapping = 223,
    ReservedE0_FE(u16),
    RequestReport = 255,
    Reserved100_FFFF(u16),
}
impl<T> From<T> for AuxiliaryDisplayUsage
where
    T: TryInto<u16>,
{
    fn from(value: T) -> Self {
        let value: u16 = value.try_into().unwrap_or(0);
        match value {
            0 => Self::Undefined,
            1 => Self::AlphanumericDisplay,
            2 => Self::AuxiliaryDisplay,
            3..32 => Self::Reserved03_1F(value),
            32 => Self::DisplayAttributesReport,
            33 => Self::ASCIICharacterSet,
            34 => Self::DataReadBack,
            35 => Self::FontReadBack,
            36 => Self::DisplayControlReport,
            37 => Self::ClearDisplay,
            38 => Self::DisplayEnable,
            39 => Self::ScreenSaverDelay,
            40 => Self::ScreenSaverEnable,
            41 => Self::VerticalScroll,
            42 => Self::HorizontalScroll,
            43 => Self::CharacterReport,
            44 => Self::DisplayData,
            45 => Self::DisplayStatus,
            46 => Self::StatNotReady,
            47 => Self::StatReady,
            48 => Self::ErrNotaloadablecharacter,
            49 => Self::ErrFontdatacannotberead,
            50 => Self::CursorPositionReport,
            51 => Self::Row,
            52 => Self::Column,
            53 => Self::Rows,
            54 => Self::Columns,
            55 => Self::CursorPixelPositioning,
            56 => Self::CursorMode,
            57 => Self::CursorEnable,
            58 => Self::CursorBlink,
            59 => Self::FontReport,
            60 => Self::FontData,
            61 => Self::CharacterWidth,
            62 => Self::CharacterHeight,
            63 => Self::CharacterSpacingHorizontal,
            64 => Self::CharacterSpacingVertical,
            65 => Self::UnicodeCharacterSet,
            66 => Self::Font7_Segment,
            67 => Self::_7_SegmentDirectMap,
            68 => Self::Font14_Segment,
            69 => Self::_14_SegmentDirectMap,
            70 => Self::DisplayBrightness,
            71 => Self::DisplayContrast,
            72 => Self::CharacterAttribute,
            73 => Self::AttributeReadback,
            74 => Self::AttributeData,
            75 => Self::CharAttrEnhance,
            76 => Self::CharAttrUnderline,
            77 => Self::CharAttrBlink,
            78..128 => Self::Reserved4E_7F(value),
            128 => Self::BitmapSizeX,
            129 => Self::BitmapSizeY,
            130 => Self::MaxBlitSize,
            131 => Self::BitDepthFormat,
            132 => Self::DisplayOrientation,
            133 => Self::PaletteReport,
            134 => Self::PaletteDataSize,
            135 => Self::PaletteDataOffset,
            136 => Self::PaletteData,
            137 => Self::Reserved89(value),
            138 => Self::BlitReport,
            139 => Self::BlitRectangleX1,
            140 => Self::BlitRectangleY1,
            141 => Self::BlitRectangleX2,
            142 => Self::BlitRectangleY2,
            143 => Self::BlitData,
            144 => Self::SoftButton,
            145 => Self::SoftButtonID,
            146 => Self::SoftButtonSide,
            147 => Self::SoftButtonOffset1,
            148 => Self::SoftButtonOffset2,
            149 => Self::SoftButtonReport,
            150..194 => Self::Reserved96_C1(value),
            194 => Self::SoftKeys,
            195..204 => Self::ReservedC3_CB(value),
            204 => Self::DisplayDataExtensions,
            205..207 => Self::ReservedCD_CE(value),
            207 => Self::CharacterMapping,
            208..221 => Self::ReservedD0_DC(value),
            221 => Self::UnicodeEquivalent,
            222 => Self::ReservedDE(value),
            223 => Self::CharacterPageMapping,
            224..255 => Self::ReservedE0_FE(value),
            255 => Self::RequestReport,
            256..=65535 => Self::Reserved100_FFFF(value),
        }
    }
}
