#[derive(Clone, Copy, PartialEq, PartialOrd, Ord, Eq, Hash, Debug, Default)]
#[non_exhaustive]
#[repr(u16)]
pub enum SensorUsage {
    #[default]
    Undefined,
    Sensor,
    Reserved02_0F,
    Biometric = 0x10,
    BiometricHumanPresence,
    BiometricHumanProximity,
    BiometricHumanTouch,
    BiometricBloodPressure,
    BiometricBodyTemperature,
    BiometricHeartRate,
    BiometricHeartRateVariability,
    BiometricPeripheralOxygenSaturation,
    BiometricRespiratoryRate,
    Reserved1A_1F,
    Electrical = 0x20,
    ElectricalCapacitance,
    ElectricalCurrent,
    ElectricalPower,
    ElectricalInductance,
    ElectricalResistance,
    ElectricalVoltage,
    ElectricalPotentiometer,
    ElectricalFrequency,
    ElectricalPeriod,
    Reserved2A_2F,
    Environmental = 0x30,
    EnvironmentalAtmosphericPressure,
    EnvironmentalHumidity,
    EnvironmentalTemperature,
    EnvironmentalWindDirection,
    EnvironmentalWindSpeed,
    EnvironmentalAirQuality,
    EnvironmentalHeatIndex,
    EnvironmentalSurfaceTemperature,
    EnvironmentalVolatileOrganicCompounds,
    EnvironmentalObjectPresence,
    EnvironmentalObjectProximity,
    Reserved3C_3F,
    Light = 0x40,
    LightAmbientLight,
    LightConsumerInfrared,
    LightInfraredLight,
    LightVisibleLight,
    LightUltravioletLight,
    Reserved46_4F,
    Location = 0x50,
    LocationBroadcast,
    LocationDeadReckoning,
    LocationGPS_GlobalPositioningSystem,
    LocationLookup,
    LocationOther,
    LocationStatic,
    LocationTriangulation,
    Reserved58_5F,
    Mechanical = 0x60,
    MechanicalBooleanSwitch,
    MechanicalBooleanSwitchArray,
    MechanicalMultivalueSwitch,
    MechanicalForce,
    MechanicalPressure,
    MechanicalStrain,
    MechanicalWeight,
    MechanicalHapticVibrator,
    MechanicalHallEffectSwitch,
    Reserved6A_6F,
    Motion = 0x70,
    MotionAccelerometer1D,
    MotionAccelerometer2D,
    MotionAccelerometer3D,
    MotionGyrometer1D,
    MotionGyrometer2D,
    MotionGyrometer3D,
    MotionMotionDetector,
    MotionSpeedometer,
    MotionAccelerometer,
    MotionGyrometer,
    MotionGravityVector,
    MotionLinearAccelerometer,
    Reserved7D_7F,
    Orientation = 0x80,
    OrientationCompass1D,
    OrientationCompass2D,
    OrientationCompass3D,
    OrientationInclinometer1D,
    OrientationInclinometer2D,
    OrientationInclinometer3D,
    OrientationDistance1D,
    OrientationDistance2D,
    OrientationDistance3D,
    OrientationDeviceOrientation,
    OrientationCompass,
    OrientationInclinometer,
    OrientationDistance,
    OrientationRelativeOrientation,
    OrientationSimpleOrientation,
    Scanner,
    ScannerBarcode,
    ScannerRFID,
    ScannerNFC,
    Reserved94_9F,
    Time = 0xA0,
    TimeAlarmTimer,
    TimeRealTimeClock,
    ReservedA3_AF,
    PersonalActivity = 0xB0,
    PersonalActivityActivityDetection,
    PersonalActivityDevicePosition,
    PersonalActivityFloorTracker,
    PersonalActivityPedometer,
    PersonalActivityStepDetection,
    ReservedB6_BF,
    OrientationExtended = 0xC0,
    OrientationExtendedGeomagneticOrientation,
    OrientationExtendedMagnetometer,
    ReservedC3_CF,
    Gesture = 0xD0,
    GestureChassisFlipGesture,
    GestureHingeFoldGesture,
    ReservedD3_DF,
    Other = 0xE0,
    OtherCustom,
    OtherGeneric,
    OtherGenericEnumerator,
    OtherHingeAngle,
    ReservedE5_EF,
    VendorReserved1 = 0xF0,
    VendorReserved2,
    VendorReserved3,
    VendorReserved4,
    VendorReserved5,
    VendorReserved6,
    VendorReserved7,
    VendorReserved8,
    VendorReserved9,
    VendorReserved10,
    VendorReserved11,
    VendorReserved12,
    VendorReserved13,
    VendorReserved14,
    VendorReserved15,
    VendorReserved16,
    Reserved100_1FF,
    Event = 0x200,
    EventSensorState,
    EventSensorEvent,
    Reserved203_2FF,
    Property = 0x300,
    PropertyFriendlyName,
    PropertyPersistentUniqueID,
    PropertySensorStatus,
    PropertyMinimumReportInterval,
    PropertySensorManufacturer,
    PropertySensorModel,
    PropertySensorSerialNumber,
    PropertySensorDescription,
    PropertySensorConnectionType,
    PropertySensorDevicePath,
    PropertyHardwareRevision,
    PropertyFirmwareVersion,
    PropertyReleaseDate,
    PropertyReportInterval,
    PropertyChangeSensitivityAbsolute,
    PropertyChangeSensitivityPercentofRange,
    PropertyChangeSensitivityPercentRelative,
    PropertyAccuracy,
    PropertyResolution,
    PropertyMaximum,
    PropertyMinimum,
    PropertyReportingState,
    PropertySamplingRate,
    PropertyResponseCurve,
    PropertyPowerState,
    PropertyMaximumFIFOEvents,
    PropertyReportLatency,
    PropertyFlushFIFOEvents,
    PropertyMaximumPowerConsumption,
    PropertyIsPrimary,
    PropertyHumanPresenceDetectionType,
    Reserved320_3FF,
    DataFieldLocation = 0x400,
    Reserved401,
    DataFieldAltitudeAntennaSeaLevel,
    DataFieldDifferentialReferenceStationID,
    DataFieldAltitudeEllipsoidError,
    DataFieldAltitudeEllipsoid,
    DataFieldAltitudeSeaLevelError,
    DataFieldAltitudeSeaLevel,
    DataFieldDifferentialGPSDataAge,
    DataFieldErrorRadius,
    DataFieldFixQuality,
    DataFieldFixType,
    DataFieldGeoidalSeparation,
    DataFieldGPSOperationMode,
    DataFieldGPSSelectionMode,
    DataFieldGPSStatus,
    DataFieldPositionDilutionofPrecision,
    DataFieldHorizontalDilutionofPrecision,
    DataFieldVerticalDilutionofPrecision,
    DataFieldLatitude,
    DataFieldLongitude,
    DataFieldTRUEHeading,
    DataFieldMagneticHeading,
    DataFieldMagneticVariation,
    DataFieldSpeed,
    DataFieldSatellitesinView,
    DataFieldSatellitesinViewAzimuth,
    DataFieldSatellitesinViewElevation,
    DataFieldSatellitesinViewIDs,
    DataFieldSatellitesinViewPRNs,
    DataFieldSatellitesinViewS_NRatios,
    DataFieldSatellitesUsedCount,
    DataFieldSatellitesUsedPRNs,
    DataFieldNMEASentence,
    DataFieldAddressLine1,
    DataFieldAddressLine2,
    DataFieldCity,
    DataFieldStateorProvince,
    DataFieldCountryorRegion,
    DataFieldPostalCode,
    Reserved428_429,
    PropertyLocation = 0x42A,
    PropertyLocationDesiredAccuracy,
    Reserved42C_42F,
    DataFieldEnvironmental = 0x430,
    DataFieldAtmosphericPressure,
    Reserved432,
    DataFieldRelativeHumidity = 0x433,
    DataFieldTemperature,
    DataFieldWindDirection,
    DataFieldWindSpeed,
    DataFieldAirQualityIndex,
    DataFieldEquivalentCO2,
    DataFieldVolatileOrganicCompoundConcentration,
    DataFieldObjectPresence,
    DataFieldObjectProximityRange,
    DataFieldObjectProximityOutofRange,
    Reserved43D_43F,
    PropertyEnvironmental = 0x440,
    PropertyReferencePressure,
    Reserved442_44F,
    DataFieldMotion = 0x450,
    DataFieldMotionState,
    DataFieldAcceleration,
    DataFieldAccelerationAxisX,
    DataFieldAccelerationAxisY,
    DataFieldAccelerationAxisZ,
    DataFieldAngularVelocity,
    DataFieldAngularVelocityaboutXAxis,
    DataFieldAngularVelocityaboutYAxis,
    DataFieldAngularVelocityaboutZAxis,
    DataFieldAngularPosition,
    DataFieldAngularPositionaboutXAxis,
    DataFieldAngularPositionaboutYAxis,
    DataFieldAngularPositionaboutZAxis,
    DataFieldMotionSpeed,
    DataFieldMotionIntensity,
    Reserved460_46F,
    DataFieldOrientation = 0x470,
    DataFieldHeading,
    DataFieldHeadingXAxis,
    DataFieldHeadingYAxis,
    DataFieldHeadingZAxis,
    DataFieldHeadingCompensatedMagneticNorth,
    DataFieldHeadingCompensatedTRUENorth,
    DataFieldHeadingMagneticNorth,
    DataFieldHeadingTRUENorth,
    DataFieldDistance,
    DataFieldDistanceXAxis,
    DataFieldDistanceYAxis,
    DataFieldDistanceZAxis,
    DataFieldDistanceOut_of_Range,
    DataFieldTilt,
    DataFieldTiltXAxis,
    DataFieldTiltYAxis,
    DataFieldTiltZAxis,
    DataFieldRotationMatrix,
    DataFieldQuaternion,
    DataFieldMagneticFlux,
    DataFieldMagneticFluxXAxis,
    DataFieldMagneticFluxYAxis,
    DataFieldMagneticFluxZAxis,
    DataFieldMagnetometerAccuracy,
    DataFieldSimpleOrientationDirection,
    Reserved48A_48F,
    DataFieldMechanical = 0x490,
    DataFieldBooleanSwitchState,
    DataFieldBooleanSwitchArrayStates,
    DataFieldMultivalueSwitchValue,
    DataFieldForce,
    DataFieldAbsolutePressure,
    DataFieldGaugePressure,
    DataFieldStrain,
    DataFieldWeight,
    Reserved499_49F,
    PropertyMechanical = 0x4A0,
    PropertyVibrationState,
    PropertyForwardVibrationSpeed,
    PropertyBackwardVibrationSpeed,
    Reserved4A4_4AF,
    FieldBiometric = 0x4B0,
    DataFieldHumanPresence,
    DataFieldHumanProximityRange,
    DataFieldHumanProximityOutofRange,
    DataFieldHumanTouchState,
    DataFieldBloodPressure,
    DataFieldBloodPressureDiastolic,
    DataFieldBloodPressureSystolic,
    DataFieldHeartRate,
    DataFieldRestingHeartRate,
    DataFieldHeartbeatInterval,
    DataFieldRespiratoryRate,
    DataFieldSpO2,
    DataFieldHumanAttentionDetected,
    DataFieldHumanHeadAzimuth,
    DataFieldHumanHeadAltitude,
    DataFieldHumanHeadRoll,
    DataFieldHumanHeadPitch,
    DataFieldHumanHeadYaw,
    DataFieldHumanCorrelationId,
    Reserved4C4_4CF,
    DataFieldLight = 0x4D0,
    DataFieldIlluminance,
    DataFieldColorTemperature,
    DataFieldChromaticity,
    DataFieldChromaticityX,
    DataFieldChromaticityY,
    DataFieldConsumerIRSentenceReceive,
    DataFieldInfraredLight,
    DataFieldRedLight,
    DataFieldGreenLight,
    DataFieldBlueLight,
    DataFieldUltravioletALight,
    DataFieldUltravioletBLight,
    DataFieldUltravioletIndex,
    DataFieldNearInfraredLight,
    PropertyLight,
    PropertyConsumerIRSentenceSend,
    Reserved4E1,
    AutoBrightnessPreferred,
    PropertyAutoColorPreferred,
    Reserved4E4_4EF,
    DataFieldScanner = 0x4F0,
    DataFieldRFIDTag40Bit,
    DataFieldNFCSentenceReceive,
    Reserved4F3_4F7,
    PropertyScanner = 0x4F8,
    PropertyNFCSentenceSend,
    Reserved4FA_4FF,
    DataFieldElectrical = 0x500,
    DataFieldCapacitance,
    DataFieldCurrent,
    DataFieldElectricalPower,
    DataFieldInductance,
    DataFieldResistance,
    DataFieldVoltage,
    DataFieldFrequency,
    DataFieldPeriod,
    DataFieldPercentofRange,
    Reserved50A_51F,
    DataFieldTime = 0x520,
    DataFieldYear,
    DataFieldMonth,
    DataFieldDay,
    DataFieldDayofWeek,
    DataFieldHour,
    DataFieldMinute,
    DataFieldSecond,
    DataFieldMillisecond,
    DataFieldTimestamp,
    DataFieldJulianDayofYear,
    DataFieldTimeSinceSystemBoot,
    Reserved52C_52F,
    PropertyTime = 0x530,
    PropertyTimeZoneOffsetfromUTC,
    PropertyTimeZoneName,
    PropertyDaylightSavingsTimeObserved,
    PropertyTimeTrimAdjustment,
    PropertyArmAlarm,
    Reserved536_53F,
    DataFieldCustom = 0x540,
    DataFieldCustomUsage,
    DataFieldCustomBooleanArray,
    DataFieldCustomValue,
    DataFieldCustomValue1,
    DataFieldCustomValue2,
    DataFieldCustomValue3,
    DataFieldCustomValue4,
    DataFieldCustomValue5,
    DataFieldCustomValue6,
    DataFieldCustomValue7,
    DataFieldCustomValue8,
    DataFieldCustomValue9,
    DataFieldCustomValue10,
    DataFieldCustomValue11,
    DataFieldCustomValue12,
    DataFieldCustomValue13,
    DataFieldCustomValue14,
    DataFieldCustomValue15,
    DataFieldCustomValue16,
    DataFieldCustomValue17,
    DataFieldCustomValue18,
    DataFieldCustomValue19,
    DataFieldCustomValue20,
    DataFieldCustomValue21,
    DataFieldCustomValue22,
    DataFieldCustomValue23,
    DataFieldCustomValue24,
    DataFieldCustomValue25,
    DataFieldCustomValue26,
    DataFieldCustomValue27,
    DataFieldCustomValue28,
    DataFieldGeneric,
    DataFieldGenericGUIDorPROPERTYKEY,
    DataFieldGenericCategoryGUID,
    DataFieldGenericTypeGUID,
    DataFieldGenericEventPROPERTYKEY,
    DataFieldGenericPropertyPROPERTYKEY,
    DataFieldGenericDataFieldPROPERTYKEY,
    DataFieldGenericEvent,
    DataFieldGenericProperty,
    DataFieldGenericDataField,
    DataFieldEnumeratorTableRowIndex,
    DataFieldEnumeratorTableRowCount,
    DataFieldGenericGUIDorPROPERTYKEYkind,
    DataFieldGenericGUID,
    DataFieldGenericPROPERTYKEY,
    DataFieldGenericTopLevelCollectionID,
    DataFieldGenericReportID,
    DataFieldGenericReportItemPositionIndex,
    DataFieldGenericFirmwareVARTYPE,
    DataFieldGenericUnitofMeasure,
    DataFieldGenericUnitExponent,
    DataFieldGenericReportSize,
    DataFieldGenericReportCount,
    Reserved577_57F,
    PropertyGeneric = 0x580,
    PropertyEnumeratorTableRowIndex,
    PropertyEnumeratorTableRowCount,
    Reserved583_58F,
    DataFieldPersonalActivity = 0x590,
    DataFieldActivityType,
    DataFieldActivityState,
    DataFieldDevicePosition,
    DataFieldStepCount,
    DataFieldStepCountReset,
    DataFieldStepDuration,
    DataFieldStepType,
    Reserved598_59F,
    PropertyMinimumActivityDetectionInterval = 0x5A0,
    PropertySupportedActivityTypes,
    PropertySubscribedActivityTypes,
    PropertySupportedStepTypes,
    PropertySubscribedStepTypes,
    PropertyFloorHeight,
    Reserved5A6_5AF,
    DataFieldCustomTypeID = 0x5B0,
    Reserved5B1_5BF,
    PropertyCustom = 0x5C0,
    PropertyCustomValue1,
    PropertyCustomValue2,
    PropertyCustomValue3,
    PropertyCustomValue4,
    PropertyCustomValue5,
    PropertyCustomValue6,
    PropertyCustomValue7,
    PropertyCustomValue8,
    PropertyCustomValue9,
    PropertyCustomValue10,
    PropertyCustomValue11,
    PropertyCustomValue12,
    PropertyCustomValue13,
    PropertyCustomValue14,
    PropertyCustomValue15,
    PropertyCustomValue16,
    Reserved5D1_5DF,
    DataFieldHinge = 0x5E0,
    DataFieldHingeAngle,
    Reserved5E2_5EF,
    DataFieldGestureSensor = 0x5F0,
    DataFieldGestureState,
    DataFieldHingeFoldInitialAngle,
    DataFieldHingeFoldFinalAngle,
    DataFieldHingeFoldContributingPanel,
    DataFieldHingeFoldType,
    Reserved5F6_7FF,
    SensorStateUndefined = 0x800,
    SensorStateReady,
    SensorStateNotAvailable,
    SensorStateNoData,
    SensorStateInitializing,
    SensorStateAccessDenied,
    SensorStateError,
    Reserved807_80F,
    SensorEventUnknown = 0x810,
    SensorEventStateChanged,
    SensorEventPropertyChanged,
    SensorEventDataUpdated,
    SensorEventPollResponse,
    SensorEventChangeSensitivity,
    SensorEventRangeMaximumReached,
    SensorEventRangeMinimumReached,
    SensorEventHighThresholdCrossUpward,
    SensorEventHighThresholdCrossDownward,
    SensorEventLowThresholdCrossUpward,
    SensorEventLowThresholdCrossDownward,
    SensorEventZeroThresholdCrossUpward,
    SensorEventZeroThresholdCrossDownward,
    SensorEventPeriodExceeded,
    SensorEventFrequencyExceeded,
    SensorEventComplexTrigger,
    Reserved821_82F,
    ConnectionTypePCIntegrated = 0x830,
    ConnectionTypePCAttached,
    ConnectionTypePCExternal,
    Reserved833_83F,
    ReportingStateReportNoEvents = 0x840,
    ReportingStateReportAllEvents,
    ReportingStateReportThresholdEvents,
    ReportingStateWakeOnNoEvents,
    ReportingStateWakeOnAllEvents,
    ReportingStateWakeOnThresholdEvents,
    ReportingStateAnytime,
    Reserved847_84F,
    PowerStateUndefined = 0x850,
    PowerStateD0FullPower,
    PowerStateD1LowPower,
    PowerStateD2StandbyPowerwithWakeup,
    PowerStateD3SleepwithWakeup,
    PowerStateD4PowerOff,
    Reserved856_85F,
    AccuracyDefault = 0x860,
    AccuracyHigh,
    AccuracyMedium,
    AccuracyLow,
    Reserved864_86F,
    FixQualityNoFix = 0x870,
    FixQualityGPS,
    FixQualityDGPS,
    Reserved873_87F,
    FixTypeNoFix = 0x880,
    FixTypeGPSSPSModeFixValid,
    FixTypeDGPSSPSModeFixValid,
    FixTypeGPSPPSModeFixValid,
    FixTypeRealTimeKinematic,
    FixTypeFloatRTK,
    FixTypeEstimated_deadreckoned,
    FixTypeManualInputMode,
    FixTypeSimulatorMode,
    Reserved889_88F,
    GPSOperationModeManual = 0x890,
    GPSOperationModeAutomatic,
    Reserved892_89F,
    GPSSelectionModeAutonomous = 0x8A0,
    GPSSelectionModeDGPS,
    GPSSelectionModeEstimated_deadreckoned,
    GPSSelectionModeManualInput,
    GPSSelectionModeSimulator,
    GPSSelectionModeDataNotValid,
    Reserved8A6_8AF,
    GPSStatusDataValid = 0x8B0,
    GPSStatusDataNotValid,
    Reserved8B2_8BF,
    DayofWeekSunday = 0x8C0,
    DayofWeekMonday,
    DayofWeekTuesday,
    DayofWeekWednesday,
    DayofWeekThursday,
    DayofWeekFriday,
    DayofWeekSaturday,
    Reserved8C7_8CF,
    KindCategory = 0x8D0,
    KindType,
    KindEvent,
    KindProperty,
    KindDataField,
    Reserved8D5_8DF,
    MagnetometerAccuracyLow = 0x8E0,
    MagnetometerAccuracyMedium,
    MagnetometerAccuracyHigh,
    Reserved8E3_8EF,
    SimpleOrientationDirectionNotRotated = 0x8F0,
    SimpleOrientationDirectionRotated90DegreesCCW,
    SimpleOrientationDirectionRotated180DegreesCCW,
    SimpleOrientationDirectionRotated270DegreesCCW,
    SimpleOrientationDirectionFaceUp,
    SimpleOrientationDirectionFaceDown,
    Reserved8F6_8FF,
    VT_NULL = 0x900,
    VT_BOOL,
    VT_UI1,
    VT_I1,
    VT_UI2,
    VT_I2,
    VT_UI4,
    VT_I4,
    VT_UI8,
    VT_I8,
    VT_R4,
    VT_R8,
    VT_WSTR,
    VT_STR,
    VT_CLSID,
    VT_VECTORVT_UI1,
    VT_F16E0,
    VT_F16E1,
    VT_F16E2,
    VT_F16E3,
    VT_F16E4,
    VT_F16E5,
    VT_F16E6,
    VT_F16E7,
    VT_F16E8,
    VT_F16E9,
    VT_F16EA,
    VT_F16EB,
    VT_F16EC,
    VT_F16ED,
    VT_F16EE,
    VT_F16EF,
    VT_F32E0,
    VT_F32E1,
    VT_F32E2,
    VT_F32E3,
    VT_F32E4,
    VT_F32E5,
    VT_F32E6,
    VT_F32E7,
    VT_F32E8,
    VT_F32E9,
    VT_F32EA,
    VT_F32EB,
    VT_F32EC,
    VT_F32ED,
    VT_F32EE,
    VT_F32EF,
    ActivityTypeUnknown,
    ActivityTypeStationary,
    ActivityTypeFidgeting,
    ActivityTypeWalking,
    ActivityTypeRunning,
    ActivityTypeInVehicle,
    ActivityTypeBiking,
    ActivityTypeIdle,
    Reserved938_93F,
    UnitNotSpecified = 0x940,
    UnitLux,
    UnitDegreesKelvin,
    UnitDegreesCelsius,
    UnitPascal,
    UnitNewton,
    UnitMeters_Second,
    UnitKilogram,
    UnitMeter,
    UnitMeters_Second_Second,
    UnitFarad,
    UnitAmpere,
    UnitWatt,
    UnitHenry,
    UnitOhm,
    UnitVolt,
    UnitHertz,
    UnitBar,
    UnitDegreesAnti_clockwise,
    UnitDegreesClockwise,
    UnitDegrees,
    UnitDegrees_Second,
    UnitDegrees_Second_Second,
    UnitKnot,
    UnitPercent,
    UnitSecond,
    UnitMillisecond,
    UnitG,
    UnitBytes,
    UnitMilligauss,
    UnitBits,
    Reserved95F,
    ActivityStateNoStateChange = 0x960,
    ActivityStateStartActivity,
    ActivityStateEndActivity,
    Reserved963_96F,
    Exponent0 = 0x970,
    Exponent1,
    Exponent2,
    Exponent3,
    Exponent4,
    Exponent5,
    Exponent6,
    Exponent7,
    Exponent8,
    Exponent9,
    ExponentA,
    ExponentB,
    ExponentC,
    ExponentD,
    ExponentE,
    ExponentF,
    DevicePositionUnknown,
    DevicePositionUnchanged,
    DevicePositionOnDesk,
    DevicePositionInHand,
    DevicePositionMovinginBag,
    DevicePositionStationaryinBag,
    Reserved986_98F,
    StepTypeUnknown = 0x990,
    StepTypeWalking,
    StepTypeRunning,
    Reserved993_99F,
    GestureStateUnknown = 0x9A0,
    GestureStateStarted,
    GestureStateCompleted,
    GestureStateCancelled,
    Reserved9A4_9AF,
    HingeFoldContributingPanelUnknown = 0x9B0,
    HingeFoldContributingPanelPanel1,
    HingeFoldContributingPanelPanel2,
    HingeFoldContributingPanelBoth,
    HingeFoldTypeUnknown,
    HingeFoldTypeIncreasing,
    HingeFoldTypeDecreasing,
    Reserved9B7_9BF,
    HumanPresenceDetectionTypeVendor_DefinedNon_Biometric = 0x9C0,
    HumanPresenceDetectionTypeVendor_DefinedBiometric,
    HumanPresenceDetectionTypeFacialBiometric,
    HumanPresenceDetectionTypeAudioBiometric,
    Reserved9C4_FFF = 0x9C4,
    ModifierChangeSensitivityAbsolute = 0x1000,
    Reserved1001_10FF = 0x1001,
    ReservedforuseasChangeSensitivityAbsolutemodifierrange1100_17FF = 0x1100,
    Reserved1800_1FFF = 0x1800,
    ModifierMaximum = 0x2000,
    Reserved2001_20FF = 0x2001,
    ReservedforuseasMaximummodifierrange2100_27FF = 0x2100,
    Reserved2800_2FFF = 0x2800,
    ModifierMinimum = 0x3000,
    Reserved3001_30FF = 0x3001,
    ReservedforuseasMinimummodifierrange3100_37FF = 0x3100,
    Reserved3800_3FFF = 0x3800,
    ModifierAccuracy = 0x4000,
    Reserved4001_40FF = 0x4001,
    ReservedforuseasAccuracymodifierrange4100_47FF = 0x4100,
    Reserved4800_4FFF = 0x4800,
    ModifierResolution = 0x5000,
    Reserved5001_50FF = 0x5001,
    ReservedforuseasResolutionmodifierrange5100_57FF = 0x5100,
    Reserved5800_5FFF = 0x5800,
    ModifierThresholdHigh = 0x6000,
    Reserved6001_60FF = 0x6001,
    ReservedforuseasThresholdHighmodifierrange6100_67FF = 0x6100,
    Reserved6800_6FFF = 0x6800,
    ModifierThresholdLow = 0x7000,
    Reserved7001_70FF = 0x7001,
    ReservedforuseasThresholdLowmodifierrange7100_77FF = 0x7100,
    Reserved7800_7FFF = 0x7800,
    ModifierCalibrationOffset = 0x8000,
    Reserved8001_80FF = 0x8001,
    ReservedforuseasCalibrationOffsetmodifierrange8100_87FF = 0x8100,
    Reserved8800_8FFF = 0x8800,
    ModifierCalibrationMultiplier = 0x9000,
    Reserved9001_90FF = 0x9001,
    ReservedforuseasCalibrationMultipliermodifierrange9100_97FF = 0x9100,
    Reserved9800_9FFF = 0x9800,
    ModifierReportInterval = 0xA000,
    ReservedA001_A0FF = 0xA001,
    ReservedforuseasReportIntervalmodifierrangeA100_A7FF = 0xA100,
    ReservedA800_AFFF = 0xA800,
    ModifierFrequencyMax = 0xB000,
    ReservedB001_B0FF = 0xB001,
    ReservedforuseasFrequencyMaxmodifierrangeB100_B7FF = 0xB100,
    ReservedB800_BFFF = 0xB800,
    ModifierPeriodMax = 0xC000,
    ReservedC001_C0FF = 0xC001,
    ReservedforuseasPeriodMaxmodifierrangeC100_C7FF = 0xC100,
    ReservedC800_CFFF = 0xC800,
    ModifierChangeSensitivityPercentofRangeD000 = 0xD000,
    ReservedD001_D0FF = 0xD001,
    ReservedforuseasChangeSensitivityPercentmodifierrangeD100_D7FF = 0xD100,
    ReservedD800_DFFF = 0xD800,
    ModifierChangeSensitivityPercentRelative = 0xE000,
    ReservedE001_E0FF = 0xE001,
    ReservedforuseasChangeSensitivityPercentmodifierrangeE100_E7FF = 0xE100,
    ReservedE800_EFFF = 0xE800,
    ModifierVendorReserved = 0xF000,
    ReservedF001_F0FF,
    ReservedforuseasVendorReservedmodifierrangeF100_F7FF = 0xF100,
    ReservedF800_FFFF = 0xF800,
}
impl<T> From<T> for SensorUsage
where
    T: TryInto<u16>,
{
    fn from(value: T) -> Self {
        let value: u16 = value.try_into().unwrap_or(0);
        match value {
            0 => Self::Undefined,
            1 => Self::Sensor,
            2..16 => Self::Reserved02_0F,
            16 => Self::Biometric,
            17 => Self::BiometricHumanPresence,
            18 => Self::BiometricHumanProximity,
            19 => Self::BiometricHumanTouch,
            20 => Self::BiometricBloodPressure,
            21 => Self::BiometricBodyTemperature,
            22 => Self::BiometricHeartRate,
            23 => Self::BiometricHeartRateVariability,
            24 => Self::BiometricPeripheralOxygenSaturation,
            25 => Self::BiometricRespiratoryRate,
            26..32 => Self::Reserved1A_1F,
            32 => Self::Electrical,
            33 => Self::ElectricalCapacitance,
            34 => Self::ElectricalCurrent,
            35 => Self::ElectricalPower,
            36 => Self::ElectricalInductance,
            37 => Self::ElectricalResistance,
            38 => Self::ElectricalVoltage,
            39 => Self::ElectricalPotentiometer,
            40 => Self::ElectricalFrequency,
            41 => Self::ElectricalPeriod,
            42..48 => Self::Reserved2A_2F,
            48 => Self::Environmental,
            49 => Self::EnvironmentalAtmosphericPressure,
            50 => Self::EnvironmentalHumidity,
            51 => Self::EnvironmentalTemperature,
            52 => Self::EnvironmentalWindDirection,
            53 => Self::EnvironmentalWindSpeed,
            54 => Self::EnvironmentalAirQuality,
            55 => Self::EnvironmentalHeatIndex,
            56 => Self::EnvironmentalSurfaceTemperature,
            57 => Self::EnvironmentalVolatileOrganicCompounds,
            58 => Self::EnvironmentalObjectPresence,
            59 => Self::EnvironmentalObjectProximity,
            60..64 => Self::Reserved3C_3F,
            64 => Self::Light,
            65 => Self::LightAmbientLight,
            66 => Self::LightConsumerInfrared,
            67 => Self::LightInfraredLight,
            68 => Self::LightVisibleLight,
            69 => Self::LightUltravioletLight,
            70..80 => Self::Reserved46_4F,
            80 => Self::Location,
            81 => Self::LocationBroadcast,
            82 => Self::LocationDeadReckoning,
            83 => Self::LocationGPS_GlobalPositioningSystem,
            84 => Self::LocationLookup,
            85 => Self::LocationOther,
            86 => Self::LocationStatic,
            87 => Self::LocationTriangulation,
            88..96 => Self::Reserved58_5F,
            96 => Self::Mechanical,
            97 => Self::MechanicalBooleanSwitch,
            98 => Self::MechanicalBooleanSwitchArray,
            99 => Self::MechanicalMultivalueSwitch,
            100 => Self::MechanicalForce,
            101 => Self::MechanicalPressure,
            102 => Self::MechanicalStrain,
            103 => Self::MechanicalWeight,
            104 => Self::MechanicalHapticVibrator,
            105 => Self::MechanicalHallEffectSwitch,
            106..112 => Self::Reserved6A_6F,
            112 => Self::Motion,
            113 => Self::MotionAccelerometer1D,
            114 => Self::MotionAccelerometer2D,
            115 => Self::MotionAccelerometer3D,
            116 => Self::MotionGyrometer1D,
            117 => Self::MotionGyrometer2D,
            118 => Self::MotionGyrometer3D,
            119 => Self::MotionMotionDetector,
            120 => Self::MotionSpeedometer,
            121 => Self::MotionAccelerometer,
            122 => Self::MotionGyrometer,
            123 => Self::MotionGravityVector,
            124 => Self::MotionLinearAccelerometer,
            125..128 => Self::Reserved7D_7F,
            128 => Self::Orientation,
            129 => Self::OrientationCompass1D,
            130 => Self::OrientationCompass2D,
            131 => Self::OrientationCompass3D,
            132 => Self::OrientationInclinometer1D,
            133 => Self::OrientationInclinometer2D,
            134 => Self::OrientationInclinometer3D,
            135 => Self::OrientationDistance1D,
            136 => Self::OrientationDistance2D,
            137 => Self::OrientationDistance3D,
            138 => Self::OrientationDeviceOrientation,
            139 => Self::OrientationCompass,
            140 => Self::OrientationInclinometer,
            141 => Self::OrientationDistance,
            142 => Self::OrientationRelativeOrientation,
            143 => Self::OrientationSimpleOrientation,
            144 => Self::Scanner,
            145 => Self::ScannerBarcode,
            146 => Self::ScannerRFID,
            147 => Self::ScannerNFC,
            148..160 => Self::Reserved94_9F,
            160 => Self::Time,
            161 => Self::TimeAlarmTimer,
            162 => Self::TimeRealTimeClock,
            163..176 => Self::ReservedA3_AF,
            176 => Self::PersonalActivity,
            177 => Self::PersonalActivityActivityDetection,
            178 => Self::PersonalActivityDevicePosition,
            179 => Self::PersonalActivityFloorTracker,
            180 => Self::PersonalActivityPedometer,
            181 => Self::PersonalActivityStepDetection,
            182..192 => Self::ReservedB6_BF,
            192 => Self::OrientationExtended,
            193 => Self::OrientationExtendedGeomagneticOrientation,
            194 => Self::OrientationExtendedMagnetometer,
            195..208 => Self::ReservedC3_CF,
            208 => Self::Gesture,
            209 => Self::GestureChassisFlipGesture,
            210 => Self::GestureHingeFoldGesture,
            211..224 => Self::ReservedD3_DF,
            224 => Self::Other,
            225 => Self::OtherCustom,
            226 => Self::OtherGeneric,
            227 => Self::OtherGenericEnumerator,
            228 => Self::OtherHingeAngle,
            229..240 => Self::ReservedE5_EF,
            240 => Self::VendorReserved1,
            241 => Self::VendorReserved2,
            242 => Self::VendorReserved3,
            243 => Self::VendorReserved4,
            244 => Self::VendorReserved5,
            245 => Self::VendorReserved6,
            246 => Self::VendorReserved7,
            247 => Self::VendorReserved8,
            248 => Self::VendorReserved9,
            249 => Self::VendorReserved10,
            250 => Self::VendorReserved11,
            251 => Self::VendorReserved12,
            252 => Self::VendorReserved13,
            253 => Self::VendorReserved14,
            254 => Self::VendorReserved15,
            255 => Self::VendorReserved16,
            256..512 => Self::Reserved100_1FF,
            512 => Self::Event,
            513 => Self::EventSensorState,
            514 => Self::EventSensorEvent,
            515..768 => Self::Reserved203_2FF,
            768 => Self::Property,
            769 => Self::PropertyFriendlyName,
            770 => Self::PropertyPersistentUniqueID,
            771 => Self::PropertySensorStatus,
            772 => Self::PropertyMinimumReportInterval,
            773 => Self::PropertySensorManufacturer,
            774 => Self::PropertySensorModel,
            775 => Self::PropertySensorSerialNumber,
            776 => Self::PropertySensorDescription,
            777 => Self::PropertySensorConnectionType,
            778 => Self::PropertySensorDevicePath,
            779 => Self::PropertyHardwareRevision,
            780 => Self::PropertyFirmwareVersion,
            781 => Self::PropertyReleaseDate,
            782 => Self::PropertyReportInterval,
            783 => Self::PropertyChangeSensitivityAbsolute,
            784 => Self::PropertyChangeSensitivityPercentofRange,
            785 => Self::PropertyChangeSensitivityPercentRelative,
            786 => Self::PropertyAccuracy,
            787 => Self::PropertyResolution,
            788 => Self::PropertyMaximum,
            789 => Self::PropertyMinimum,
            790 => Self::PropertyReportingState,
            791 => Self::PropertySamplingRate,
            792 => Self::PropertyResponseCurve,
            793 => Self::PropertyPowerState,
            794 => Self::PropertyMaximumFIFOEvents,
            795 => Self::PropertyReportLatency,
            796 => Self::PropertyFlushFIFOEvents,
            797 => Self::PropertyMaximumPowerConsumption,
            798 => Self::PropertyIsPrimary,
            799 => Self::PropertyHumanPresenceDetectionType,
            800..1024 => Self::Reserved320_3FF,
            1024 => Self::DataFieldLocation,
            1025 => Self::Reserved401,
            1026 => Self::DataFieldAltitudeAntennaSeaLevel,
            1027 => Self::DataFieldDifferentialReferenceStationID,
            1028 => Self::DataFieldAltitudeEllipsoidError,
            1029 => Self::DataFieldAltitudeEllipsoid,
            1030 => Self::DataFieldAltitudeSeaLevelError,
            1031 => Self::DataFieldAltitudeSeaLevel,
            1032 => Self::DataFieldDifferentialGPSDataAge,
            1033 => Self::DataFieldErrorRadius,
            1034 => Self::DataFieldFixQuality,
            1035 => Self::DataFieldFixType,
            1036 => Self::DataFieldGeoidalSeparation,
            1037 => Self::DataFieldGPSOperationMode,
            1038 => Self::DataFieldGPSSelectionMode,
            1039 => Self::DataFieldGPSStatus,
            1040 => Self::DataFieldPositionDilutionofPrecision,
            1041 => Self::DataFieldHorizontalDilutionofPrecision,
            1042 => Self::DataFieldVerticalDilutionofPrecision,
            1043 => Self::DataFieldLatitude,
            1044 => Self::DataFieldLongitude,
            1045 => Self::DataFieldTRUEHeading,
            1046 => Self::DataFieldMagneticHeading,
            1047 => Self::DataFieldMagneticVariation,
            1048 => Self::DataFieldSpeed,
            1049 => Self::DataFieldSatellitesinView,
            1050 => Self::DataFieldSatellitesinViewAzimuth,
            1051 => Self::DataFieldSatellitesinViewElevation,
            1052 => Self::DataFieldSatellitesinViewIDs,
            1053 => Self::DataFieldSatellitesinViewPRNs,
            1054 => Self::DataFieldSatellitesinViewS_NRatios,
            1055 => Self::DataFieldSatellitesUsedCount,
            1056 => Self::DataFieldSatellitesUsedPRNs,
            1057 => Self::DataFieldNMEASentence,
            1058 => Self::DataFieldAddressLine1,
            1059 => Self::DataFieldAddressLine2,
            1060 => Self::DataFieldCity,
            1061 => Self::DataFieldStateorProvince,
            1062 => Self::DataFieldCountryorRegion,
            1063 => Self::DataFieldPostalCode,
            1064..1066 => Self::Reserved428_429,
            1066 => Self::PropertyLocation,
            1067 => Self::PropertyLocationDesiredAccuracy,
            1068..1072 => Self::Reserved42C_42F,
            1072 => Self::DataFieldEnvironmental,
            1073 => Self::DataFieldAtmosphericPressure,
            1074 => Self::Reserved432,
            1075 => Self::DataFieldRelativeHumidity,
            1076 => Self::DataFieldTemperature,
            1077 => Self::DataFieldWindDirection,
            1078 => Self::DataFieldWindSpeed,
            1079 => Self::DataFieldAirQualityIndex,
            1080 => Self::DataFieldEquivalentCO2,
            1081 => Self::DataFieldVolatileOrganicCompoundConcentration,
            1082 => Self::DataFieldObjectPresence,
            1083 => Self::DataFieldObjectProximityRange,
            1084 => Self::DataFieldObjectProximityOutofRange,
            1085..1088 => Self::Reserved43D_43F,
            1088 => Self::PropertyEnvironmental,
            1089 => Self::PropertyReferencePressure,
            1090..1104 => Self::Reserved442_44F,
            1104 => Self::DataFieldMotion,
            1105 => Self::DataFieldMotionState,
            1106 => Self::DataFieldAcceleration,
            1107 => Self::DataFieldAccelerationAxisX,
            1108 => Self::DataFieldAccelerationAxisY,
            1109 => Self::DataFieldAccelerationAxisZ,
            1110 => Self::DataFieldAngularVelocity,
            1111 => Self::DataFieldAngularVelocityaboutXAxis,
            1112 => Self::DataFieldAngularVelocityaboutYAxis,
            1113 => Self::DataFieldAngularVelocityaboutZAxis,
            1114 => Self::DataFieldAngularPosition,
            1115 => Self::DataFieldAngularPositionaboutXAxis,
            1116 => Self::DataFieldAngularPositionaboutYAxis,
            1117 => Self::DataFieldAngularPositionaboutZAxis,
            1118 => Self::DataFieldMotionSpeed,
            1119 => Self::DataFieldMotionIntensity,
            1120..1136 => Self::Reserved460_46F,
            1136 => Self::DataFieldOrientation,
            1137 => Self::DataFieldHeading,
            1138 => Self::DataFieldHeadingXAxis,
            1139 => Self::DataFieldHeadingYAxis,
            1140 => Self::DataFieldHeadingZAxis,
            1141 => Self::DataFieldHeadingCompensatedMagneticNorth,
            1142 => Self::DataFieldHeadingCompensatedTRUENorth,
            1143 => Self::DataFieldHeadingMagneticNorth,
            1144 => Self::DataFieldHeadingTRUENorth,
            1145 => Self::DataFieldDistance,
            1146 => Self::DataFieldDistanceXAxis,
            1147 => Self::DataFieldDistanceYAxis,
            1148 => Self::DataFieldDistanceZAxis,
            1149 => Self::DataFieldDistanceOut_of_Range,
            1150 => Self::DataFieldTilt,
            1151 => Self::DataFieldTiltXAxis,
            1152 => Self::DataFieldTiltYAxis,
            1153 => Self::DataFieldTiltZAxis,
            1154 => Self::DataFieldRotationMatrix,
            1155 => Self::DataFieldQuaternion,
            1156 => Self::DataFieldMagneticFlux,
            1157 => Self::DataFieldMagneticFluxXAxis,
            1158 => Self::DataFieldMagneticFluxYAxis,
            1159 => Self::DataFieldMagneticFluxZAxis,
            1160 => Self::DataFieldMagnetometerAccuracy,
            1161 => Self::DataFieldSimpleOrientationDirection,
            1162..1168 => Self::Reserved48A_48F,
            1168 => Self::DataFieldMechanical,
            1169 => Self::DataFieldBooleanSwitchState,
            1170 => Self::DataFieldBooleanSwitchArrayStates,
            1171 => Self::DataFieldMultivalueSwitchValue,
            1172 => Self::DataFieldForce,
            1173 => Self::DataFieldAbsolutePressure,
            1174 => Self::DataFieldGaugePressure,
            1175 => Self::DataFieldStrain,
            1176 => Self::DataFieldWeight,
            1177..1184 => Self::Reserved499_49F,
            1184 => Self::PropertyMechanical,
            1185 => Self::PropertyVibrationState,
            1186 => Self::PropertyForwardVibrationSpeed,
            1187 => Self::PropertyBackwardVibrationSpeed,
            1188..1200 => Self::Reserved4A4_4AF,
            1200 => Self::FieldBiometric,
            1201 => Self::DataFieldHumanPresence,
            1202 => Self::DataFieldHumanProximityRange,
            1203 => Self::DataFieldHumanProximityOutofRange,
            1204 => Self::DataFieldHumanTouchState,
            1205 => Self::DataFieldBloodPressure,
            1206 => Self::DataFieldBloodPressureDiastolic,
            1207 => Self::DataFieldBloodPressureSystolic,
            1208 => Self::DataFieldHeartRate,
            1209 => Self::DataFieldRestingHeartRate,
            1210 => Self::DataFieldHeartbeatInterval,
            1211 => Self::DataFieldRespiratoryRate,
            1212 => Self::DataFieldSpO2,
            1213 => Self::DataFieldHumanAttentionDetected,
            1214 => Self::DataFieldHumanHeadAzimuth,
            1215 => Self::DataFieldHumanHeadAltitude,
            1216 => Self::DataFieldHumanHeadRoll,
            1217 => Self::DataFieldHumanHeadPitch,
            1218 => Self::DataFieldHumanHeadYaw,
            1219 => Self::DataFieldHumanCorrelationId,
            1220..1232 => Self::Reserved4C4_4CF,
            1232 => Self::DataFieldLight,
            1233 => Self::DataFieldIlluminance,
            1234 => Self::DataFieldColorTemperature,
            1235 => Self::DataFieldChromaticity,
            1236 => Self::DataFieldChromaticityX,
            1237 => Self::DataFieldChromaticityY,
            1238 => Self::DataFieldConsumerIRSentenceReceive,
            1239 => Self::DataFieldInfraredLight,
            1240 => Self::DataFieldRedLight,
            1241 => Self::DataFieldGreenLight,
            1242 => Self::DataFieldBlueLight,
            1243 => Self::DataFieldUltravioletALight,
            1244 => Self::DataFieldUltravioletBLight,
            1245 => Self::DataFieldUltravioletIndex,
            1246 => Self::DataFieldNearInfraredLight,
            1247 => Self::PropertyLight,
            1248 => Self::PropertyConsumerIRSentenceSend,
            1249 => Self::Reserved4E1,
            1250 => Self::AutoBrightnessPreferred,
            1251 => Self::PropertyAutoColorPreferred,
            1252..1264 => Self::Reserved4E4_4EF,
            1264 => Self::DataFieldScanner,
            1265 => Self::DataFieldRFIDTag40Bit,
            1266 => Self::DataFieldNFCSentenceReceive,
            1267..1272 => Self::Reserved4F3_4F7,
            1272 => Self::PropertyScanner,
            1273 => Self::PropertyNFCSentenceSend,
            1274..1280 => Self::Reserved4FA_4FF,
            1280 => Self::DataFieldElectrical,
            1281 => Self::DataFieldCapacitance,
            1282 => Self::DataFieldCurrent,
            1283 => Self::DataFieldElectricalPower,
            1284 => Self::DataFieldInductance,
            1285 => Self::DataFieldResistance,
            1286 => Self::DataFieldVoltage,
            1287 => Self::DataFieldFrequency,
            1288 => Self::DataFieldPeriod,
            1289 => Self::DataFieldPercentofRange,
            1290..1312 => Self::Reserved50A_51F,
            1312 => Self::DataFieldTime,
            1313 => Self::DataFieldYear,
            1314 => Self::DataFieldMonth,
            1315 => Self::DataFieldDay,
            1316 => Self::DataFieldDayofWeek,
            1317 => Self::DataFieldHour,
            1318 => Self::DataFieldMinute,
            1319 => Self::DataFieldSecond,
            1320 => Self::DataFieldMillisecond,
            1321 => Self::DataFieldTimestamp,
            1322 => Self::DataFieldJulianDayofYear,
            1323 => Self::DataFieldTimeSinceSystemBoot,
            1324..1328 => Self::Reserved52C_52F,
            1328 => Self::PropertyTime,
            1329 => Self::PropertyTimeZoneOffsetfromUTC,
            1330 => Self::PropertyTimeZoneName,
            1331 => Self::PropertyDaylightSavingsTimeObserved,
            1332 => Self::PropertyTimeTrimAdjustment,
            1333 => Self::PropertyArmAlarm,
            1334..1344 => Self::Reserved536_53F,
            1344 => Self::DataFieldCustom,
            1345 => Self::DataFieldCustomUsage,
            1346 => Self::DataFieldCustomBooleanArray,
            1347 => Self::DataFieldCustomValue,
            1348 => Self::DataFieldCustomValue1,
            1349 => Self::DataFieldCustomValue2,
            1350 => Self::DataFieldCustomValue3,
            1351 => Self::DataFieldCustomValue4,
            1352 => Self::DataFieldCustomValue5,
            1353 => Self::DataFieldCustomValue6,
            1354 => Self::DataFieldCustomValue7,
            1355 => Self::DataFieldCustomValue8,
            1356 => Self::DataFieldCustomValue9,
            1357 => Self::DataFieldCustomValue10,
            1358 => Self::DataFieldCustomValue11,
            1359 => Self::DataFieldCustomValue12,
            1360 => Self::DataFieldCustomValue13,
            1361 => Self::DataFieldCustomValue14,
            1362 => Self::DataFieldCustomValue15,
            1363 => Self::DataFieldCustomValue16,
            1364 => Self::DataFieldCustomValue17,
            1365 => Self::DataFieldCustomValue18,
            1366 => Self::DataFieldCustomValue19,
            1367 => Self::DataFieldCustomValue20,
            1368 => Self::DataFieldCustomValue21,
            1369 => Self::DataFieldCustomValue22,
            1370 => Self::DataFieldCustomValue23,
            1371 => Self::DataFieldCustomValue24,
            1372 => Self::DataFieldCustomValue25,
            1373 => Self::DataFieldCustomValue26,
            1374 => Self::DataFieldCustomValue27,
            1375 => Self::DataFieldCustomValue28,
            1376 => Self::DataFieldGeneric,
            1377 => Self::DataFieldGenericGUIDorPROPERTYKEY,
            1378 => Self::DataFieldGenericCategoryGUID,
            1379 => Self::DataFieldGenericTypeGUID,
            1380 => Self::DataFieldGenericEventPROPERTYKEY,
            1381 => Self::DataFieldGenericPropertyPROPERTYKEY,
            1382 => Self::DataFieldGenericDataFieldPROPERTYKEY,
            1383 => Self::DataFieldGenericEvent,
            1384 => Self::DataFieldGenericProperty,
            1385 => Self::DataFieldGenericDataField,
            1386 => Self::DataFieldEnumeratorTableRowIndex,
            1387 => Self::DataFieldEnumeratorTableRowCount,
            1388 => Self::DataFieldGenericGUIDorPROPERTYKEYkind,
            1389 => Self::DataFieldGenericGUID,
            1390 => Self::DataFieldGenericPROPERTYKEY,
            1391 => Self::DataFieldGenericTopLevelCollectionID,
            1392 => Self::DataFieldGenericReportID,
            1393 => Self::DataFieldGenericReportItemPositionIndex,
            1394 => Self::DataFieldGenericFirmwareVARTYPE,
            1395 => Self::DataFieldGenericUnitofMeasure,
            1396 => Self::DataFieldGenericUnitExponent,
            1397 => Self::DataFieldGenericReportSize,
            1398 => Self::DataFieldGenericReportCount,
            1399..1408 => Self::Reserved577_57F,
            1408 => Self::PropertyGeneric,
            1409 => Self::PropertyEnumeratorTableRowIndex,
            1410 => Self::PropertyEnumeratorTableRowCount,
            1411..1424 => Self::Reserved583_58F,
            1424 => Self::DataFieldPersonalActivity,
            1425 => Self::DataFieldActivityType,
            1426 => Self::DataFieldActivityState,
            1427 => Self::DataFieldDevicePosition,
            1428 => Self::DataFieldStepCount,
            1429 => Self::DataFieldStepCountReset,
            1430 => Self::DataFieldStepDuration,
            1431 => Self::DataFieldStepType,
            1432..1440 => Self::Reserved598_59F,
            1440 => Self::PropertyMinimumActivityDetectionInterval,
            1441 => Self::PropertySupportedActivityTypes,
            1442 => Self::PropertySubscribedActivityTypes,
            1443 => Self::PropertySupportedStepTypes,
            1444 => Self::PropertySubscribedStepTypes,
            1445 => Self::PropertyFloorHeight,
            1446..1456 => Self::Reserved5A6_5AF,
            1456 => Self::DataFieldCustomTypeID,
            1457..1472 => Self::Reserved5B1_5BF,
            1472 => Self::PropertyCustom,
            1473 => Self::PropertyCustomValue1,
            1474 => Self::PropertyCustomValue2,
            1475 => Self::PropertyCustomValue3,
            1476 => Self::PropertyCustomValue4,
            1477 => Self::PropertyCustomValue5,
            1478 => Self::PropertyCustomValue6,
            1479 => Self::PropertyCustomValue7,
            1480 => Self::PropertyCustomValue8,
            1481 => Self::PropertyCustomValue9,
            1482 => Self::PropertyCustomValue10,
            1483 => Self::PropertyCustomValue11,
            1484 => Self::PropertyCustomValue12,
            1485 => Self::PropertyCustomValue13,
            1486 => Self::PropertyCustomValue14,
            1487 => Self::PropertyCustomValue15,
            1488 => Self::PropertyCustomValue16,
            1489..1504 => Self::Reserved5D1_5DF,
            1504 => Self::DataFieldHinge,
            1505 => Self::DataFieldHingeAngle,
            1506..1520 => Self::Reserved5E2_5EF,
            1520 => Self::DataFieldGestureSensor,
            1521 => Self::DataFieldGestureState,
            1522 => Self::DataFieldHingeFoldInitialAngle,
            1523 => Self::DataFieldHingeFoldFinalAngle,
            1524 => Self::DataFieldHingeFoldContributingPanel,
            1525 => Self::DataFieldHingeFoldType,
            1526..2048 => Self::Reserved5F6_7FF,
            2048 => Self::SensorStateUndefined,
            2049 => Self::SensorStateReady,
            2050 => Self::SensorStateNotAvailable,
            2051 => Self::SensorStateNoData,
            2052 => Self::SensorStateInitializing,
            2053 => Self::SensorStateAccessDenied,
            2054 => Self::SensorStateError,
            2055..2064 => Self::Reserved807_80F,
            2064 => Self::SensorEventUnknown,
            2065 => Self::SensorEventStateChanged,
            2066 => Self::SensorEventPropertyChanged,
            2067 => Self::SensorEventDataUpdated,
            2068 => Self::SensorEventPollResponse,
            2069 => Self::SensorEventChangeSensitivity,
            2070 => Self::SensorEventRangeMaximumReached,
            2071 => Self::SensorEventRangeMinimumReached,
            2072 => Self::SensorEventHighThresholdCrossUpward,
            2073 => Self::SensorEventHighThresholdCrossDownward,
            2074 => Self::SensorEventLowThresholdCrossUpward,
            2075 => Self::SensorEventLowThresholdCrossDownward,
            2076 => Self::SensorEventZeroThresholdCrossUpward,
            2077 => Self::SensorEventZeroThresholdCrossDownward,
            2078 => Self::SensorEventPeriodExceeded,
            2079 => Self::SensorEventFrequencyExceeded,
            2080 => Self::SensorEventComplexTrigger,
            2081..2096 => Self::Reserved821_82F,
            2096 => Self::ConnectionTypePCIntegrated,
            2097 => Self::ConnectionTypePCAttached,
            2098 => Self::ConnectionTypePCExternal,
            2099..2112 => Self::Reserved833_83F,
            2112 => Self::ReportingStateReportNoEvents,
            2113 => Self::ReportingStateReportAllEvents,
            2114 => Self::ReportingStateReportThresholdEvents,
            2115 => Self::ReportingStateWakeOnNoEvents,
            2116 => Self::ReportingStateWakeOnAllEvents,
            2117 => Self::ReportingStateWakeOnThresholdEvents,
            2118 => Self::ReportingStateAnytime,
            2119..2128 => Self::Reserved847_84F,
            2128 => Self::PowerStateUndefined,
            2129 => Self::PowerStateD0FullPower,
            2130 => Self::PowerStateD1LowPower,
            2131 => Self::PowerStateD2StandbyPowerwithWakeup,
            2132 => Self::PowerStateD3SleepwithWakeup,
            2133 => Self::PowerStateD4PowerOff,
            2134..2144 => Self::Reserved856_85F,
            2144 => Self::AccuracyDefault,
            2145 => Self::AccuracyHigh,
            2146 => Self::AccuracyMedium,
            2147 => Self::AccuracyLow,
            2148..2160 => Self::Reserved864_86F,
            2160 => Self::FixQualityNoFix,
            2161 => Self::FixQualityGPS,
            2162 => Self::FixQualityDGPS,
            2163..2176 => Self::Reserved873_87F,
            2176 => Self::FixTypeNoFix,
            2177 => Self::FixTypeGPSSPSModeFixValid,
            2178 => Self::FixTypeDGPSSPSModeFixValid,
            2179 => Self::FixTypeGPSPPSModeFixValid,
            2180 => Self::FixTypeRealTimeKinematic,
            2181 => Self::FixTypeFloatRTK,
            2182 => Self::FixTypeEstimated_deadreckoned,
            2183 => Self::FixTypeManualInputMode,
            2184 => Self::FixTypeSimulatorMode,
            2185..2192 => Self::Reserved889_88F,
            2192 => Self::GPSOperationModeManual,
            2193 => Self::GPSOperationModeAutomatic,
            2194..2208 => Self::Reserved892_89F,
            2208 => Self::GPSSelectionModeAutonomous,
            2209 => Self::GPSSelectionModeDGPS,
            2210 => Self::GPSSelectionModeEstimated_deadreckoned,
            2211 => Self::GPSSelectionModeManualInput,
            2212 => Self::GPSSelectionModeSimulator,
            2213 => Self::GPSSelectionModeDataNotValid,
            2214..2224 => Self::Reserved8A6_8AF,
            2224 => Self::GPSStatusDataValid,
            2225 => Self::GPSStatusDataNotValid,
            2226..2240 => Self::Reserved8B2_8BF,
            2240 => Self::DayofWeekSunday,
            2241 => Self::DayofWeekMonday,
            2242 => Self::DayofWeekTuesday,
            2243 => Self::DayofWeekWednesday,
            2244 => Self::DayofWeekThursday,
            2245 => Self::DayofWeekFriday,
            2246 => Self::DayofWeekSaturday,
            2247..2256 => Self::Reserved8C7_8CF,
            2256 => Self::KindCategory,
            2257 => Self::KindType,
            2258 => Self::KindEvent,
            2259 => Self::KindProperty,
            2260 => Self::KindDataField,
            2261..2272 => Self::Reserved8D5_8DF,
            2272 => Self::MagnetometerAccuracyLow,
            2273 => Self::MagnetometerAccuracyMedium,
            2274 => Self::MagnetometerAccuracyHigh,
            2275..2288 => Self::Reserved8E3_8EF,
            2288 => Self::SimpleOrientationDirectionNotRotated,
            2289 => Self::SimpleOrientationDirectionRotated90DegreesCCW,
            2290 => Self::SimpleOrientationDirectionRotated180DegreesCCW,
            2291 => Self::SimpleOrientationDirectionRotated270DegreesCCW,
            2292 => Self::SimpleOrientationDirectionFaceUp,
            2293 => Self::SimpleOrientationDirectionFaceDown,
            2294..2304 => Self::Reserved8F6_8FF,
            2304 => Self::VT_NULL,
            2305 => Self::VT_BOOL,
            2306 => Self::VT_UI1,
            2307 => Self::VT_I1,
            2308 => Self::VT_UI2,
            2309 => Self::VT_I2,
            2310 => Self::VT_UI4,
            2311 => Self::VT_I4,
            2312 => Self::VT_UI8,
            2313 => Self::VT_I8,
            2314 => Self::VT_R4,
            2315 => Self::VT_R8,
            2316 => Self::VT_WSTR,
            2317 => Self::VT_STR,
            2318 => Self::VT_CLSID,
            2319 => Self::VT_VECTORVT_UI1,
            2320 => Self::VT_F16E0,
            2321 => Self::VT_F16E1,
            2322 => Self::VT_F16E2,
            2323 => Self::VT_F16E3,
            2324 => Self::VT_F16E4,
            2325 => Self::VT_F16E5,
            2326 => Self::VT_F16E6,
            2327 => Self::VT_F16E7,
            2328 => Self::VT_F16E8,
            2329 => Self::VT_F16E9,
            2330 => Self::VT_F16EA,
            2331 => Self::VT_F16EB,
            2332 => Self::VT_F16EC,
            2333 => Self::VT_F16ED,
            2334 => Self::VT_F16EE,
            2335 => Self::VT_F16EF,
            2336 => Self::VT_F32E0,
            2337 => Self::VT_F32E1,
            2338 => Self::VT_F32E2,
            2339 => Self::VT_F32E3,
            2340 => Self::VT_F32E4,
            2341 => Self::VT_F32E5,
            2342 => Self::VT_F32E6,
            2343 => Self::VT_F32E7,
            2344 => Self::VT_F32E8,
            2345 => Self::VT_F32E9,
            2346 => Self::VT_F32EA,
            2347 => Self::VT_F32EB,
            2348 => Self::VT_F32EC,
            2349 => Self::VT_F32ED,
            2350 => Self::VT_F32EE,
            2351 => Self::VT_F32EF,
            2352 => Self::ActivityTypeUnknown,
            2353 => Self::ActivityTypeStationary,
            2354 => Self::ActivityTypeFidgeting,
            2355 => Self::ActivityTypeWalking,
            2356 => Self::ActivityTypeRunning,
            2357 => Self::ActivityTypeInVehicle,
            2358 => Self::ActivityTypeBiking,
            2359 => Self::ActivityTypeIdle,
            2360..2368 => Self::Reserved938_93F,
            2368 => Self::UnitNotSpecified,
            2369 => Self::UnitLux,
            2370 => Self::UnitDegreesKelvin,
            2371 => Self::UnitDegreesCelsius,
            2372 => Self::UnitPascal,
            2373 => Self::UnitNewton,
            2374 => Self::UnitMeters_Second,
            2375 => Self::UnitKilogram,
            2376 => Self::UnitMeter,
            2377 => Self::UnitMeters_Second_Second,
            2378 => Self::UnitFarad,
            2379 => Self::UnitAmpere,
            2380 => Self::UnitWatt,
            2381 => Self::UnitHenry,
            2382 => Self::UnitOhm,
            2383 => Self::UnitVolt,
            2384 => Self::UnitHertz,
            2385 => Self::UnitBar,
            2386 => Self::UnitDegreesAnti_clockwise,
            2387 => Self::UnitDegreesClockwise,
            2388 => Self::UnitDegrees,
            2389 => Self::UnitDegrees_Second,
            2390 => Self::UnitDegrees_Second_Second,
            2391 => Self::UnitKnot,
            2392 => Self::UnitPercent,
            2393 => Self::UnitSecond,
            2394 => Self::UnitMillisecond,
            2395 => Self::UnitG,
            2396 => Self::UnitBytes,
            2397 => Self::UnitMilligauss,
            2398 => Self::UnitBits,
            2399 => Self::Reserved95F,
            2400 => Self::ActivityStateNoStateChange,
            2401 => Self::ActivityStateStartActivity,
            2402 => Self::ActivityStateEndActivity,
            2403..2416 => Self::Reserved963_96F,
            2416 => Self::Exponent0,
            2417 => Self::Exponent1,
            2418 => Self::Exponent2,
            2419 => Self::Exponent3,
            2420 => Self::Exponent4,
            2421 => Self::Exponent5,
            2422 => Self::Exponent6,
            2423 => Self::Exponent7,
            2424 => Self::Exponent8,
            2425 => Self::Exponent9,
            2426 => Self::ExponentA,
            2427 => Self::ExponentB,
            2428 => Self::ExponentC,
            2429 => Self::ExponentD,
            2430 => Self::ExponentE,
            2431 => Self::ExponentF,
            2432 => Self::DevicePositionUnknown,
            2433 => Self::DevicePositionUnchanged,
            2434 => Self::DevicePositionOnDesk,
            2435 => Self::DevicePositionInHand,
            2436 => Self::DevicePositionMovinginBag,
            2437 => Self::DevicePositionStationaryinBag,
            2438..2448 => Self::Reserved986_98F,
            2448 => Self::StepTypeUnknown,
            2449 => Self::StepTypeWalking,
            2450 => Self::StepTypeRunning,
            2451..2464 => Self::Reserved993_99F,
            2464 => Self::GestureStateUnknown,
            2465 => Self::GestureStateStarted,
            2466 => Self::GestureStateCompleted,
            2467 => Self::GestureStateCancelled,
            2468..2480 => Self::Reserved9A4_9AF,
            2480 => Self::HingeFoldContributingPanelUnknown,
            2481 => Self::HingeFoldContributingPanelPanel1,
            2482 => Self::HingeFoldContributingPanelPanel2,
            2483 => Self::HingeFoldContributingPanelBoth,
            2484 => Self::HingeFoldTypeUnknown,
            2485 => Self::HingeFoldTypeIncreasing,
            2486 => Self::HingeFoldTypeDecreasing,
            2487..2496 => Self::Reserved9B7_9BF,
            2496 => Self::HumanPresenceDetectionTypeVendor_DefinedNon_Biometric,
            2497 => Self::HumanPresenceDetectionTypeVendor_DefinedBiometric,
            2498 => Self::HumanPresenceDetectionTypeFacialBiometric,
            2499 => Self::HumanPresenceDetectionTypeAudioBiometric,
            2500..4096 => Self::Reserved9C4_FFF,
            4096 => Self::ModifierChangeSensitivityAbsolute,
            4097..4352 => Self::Reserved1001_10FF,
            4352..6144 => Self::ReservedforuseasChangeSensitivityAbsolutemodifierrange1100_17FF,
            6144..8192 => Self::Reserved1800_1FFF,
            8192 => Self::ModifierMaximum,
            8193..8448 => Self::Reserved2001_20FF,
            8448..10240 => Self::ReservedforuseasMaximummodifierrange2100_27FF,
            10240..12288 => Self::Reserved2800_2FFF,
            12288 => Self::ModifierMinimum,
            12289..12544 => Self::Reserved3001_30FF,
            12544..14336 => Self::ReservedforuseasMinimummodifierrange3100_37FF,
            14336..16384 => Self::Reserved3800_3FFF,
            16384 => Self::ModifierAccuracy,
            16385..16640 => Self::Reserved4001_40FF,
            16640..18432 => Self::ReservedforuseasAccuracymodifierrange4100_47FF,
            18432..20480 => Self::Reserved4800_4FFF,
            20480 => Self::ModifierResolution,
            20481..20736 => Self::Reserved5001_50FF,
            20736..22528 => Self::ReservedforuseasResolutionmodifierrange5100_57FF,
            22528..24576 => Self::Reserved5800_5FFF,
            24576 => Self::ModifierThresholdHigh,
            24577..24832 => Self::Reserved6001_60FF,
            24832..26624 => Self::ReservedforuseasThresholdHighmodifierrange6100_67FF,
            26624..28672 => Self::Reserved6800_6FFF,
            28672 => Self::ModifierThresholdLow,
            28673..28928 => Self::Reserved7001_70FF,
            28928..30720 => Self::ReservedforuseasThresholdLowmodifierrange7100_77FF,
            30720..32768 => Self::Reserved7800_7FFF,
            32768 => Self::ModifierCalibrationOffset,
            32769..33024 => Self::Reserved8001_80FF,
            33024..34816 => Self::ReservedforuseasCalibrationOffsetmodifierrange8100_87FF,
            34816..36864 => Self::Reserved8800_8FFF,
            36864 => Self::ModifierCalibrationMultiplier,
            36865..37120 => Self::Reserved9001_90FF,
            37120..38912 => Self::ReservedforuseasCalibrationMultipliermodifierrange9100_97FF,
            38912..40960 => Self::Reserved9800_9FFF,
            40960 => Self::ModifierReportInterval,
            40961..41216 => Self::ReservedA001_A0FF,
            41216..43008 => Self::ReservedforuseasReportIntervalmodifierrangeA100_A7FF,
            43008..45056 => Self::ReservedA800_AFFF,
            45056 => Self::ModifierFrequencyMax,
            45057..45312 => Self::ReservedB001_B0FF,
            45312..47104 => Self::ReservedforuseasFrequencyMaxmodifierrangeB100_B7FF,
            47104..49152 => Self::ReservedB800_BFFF,
            49152 => Self::ModifierPeriodMax,
            49153..49408 => Self::ReservedC001_C0FF,
            49408..51200 => Self::ReservedforuseasPeriodMaxmodifierrangeC100_C7FF,
            51200..53248 => Self::ReservedC800_CFFF,
            53248 => Self::ModifierChangeSensitivityPercentofRangeD000,
            53249..53504 => Self::ReservedD001_D0FF,
            53504..55296 => Self::ReservedforuseasChangeSensitivityPercentmodifierrangeD100_D7FF,
            55296..57344 => Self::ReservedD800_DFFF,
            57344 => Self::ModifierChangeSensitivityPercentRelative,
            57345..57600 => Self::ReservedE001_E0FF,
            57600..59392 => Self::ReservedforuseasChangeSensitivityPercentmodifierrangeE100_E7FF,
            59392..61440 => Self::ReservedE800_EFFF,
            61440 => Self::ModifierVendorReserved,
            61441..61696 => Self::ReservedF001_F0FF,
            61696..63488 => Self::ReservedforuseasVendorReservedmodifierrangeF100_F7FF,
            63488..=65535 => Self::ReservedF800_FFFF,
        }
    }
}
