#[derive(Clone, Copy, PartialEq, PartialOrd, Ord, Eq, Hash, Debug, Default)]
#[non_exhaustive]
#[repr(u16)]
pub enum SensorUsage {
    #[default]
    Undefined,
    Sensor,
    Reserved02_0F,
    Biometric = 0x10,
    BiometricHumanPresence,
    BiometricHumanProximity,
    BiometricHumanTouch,
    BiometricBloodPressure,
    BiometricBodyTemperature,
    BiometricHeartRate,
    BiometricHeartRateVariability,
    BiometricPeripheralOxygenSaturation,
    BiometricRespiratoryRate,
    Reserved1A_1F,
    Electrical = 0x20,
    ElectricalCapacitance,
    ElectricalCurrent,
    ElectricalPower,
    ElectricalInductance,
    ElectricalResistance,
    ElectricalVoltage,
    ElectricalPotentiometer,
    ElectricalFrequency,
    ElectricalPeriod,
    Reserved2A_2F,
    Environmental = 0x30,
    EnvironmentalAtmosphericPressure,
    EnvironmentalHumidity,
    EnvironmentalTemperature,
    EnvironmentalWindDirection,
    EnvironmentalWindSpeed,
    EnvironmentalAirQuality,
    EnvironmentalHeatIndex,
    EnvironmentalSurfaceTemperature,
    EnvironmentalVolatileOrganicCompounds,
    EnvironmentalObjectPresence,
    EnvironmentalObjectProximity,
    Reserved3C_3F,
    Light = 0x40,
    LightAmbientLight,
    LightConsumerInfrared,
    LightInfraredLight,
    LightVisibleLight,
    LightUltravioletLight,
    Reserved46_4F,
    Location = 0x50,
    LocationBroadcast,
    LocationDeadReckoning,
    LocationGPS_GlobalPositioningSystem,
    LocationLookup,
    LocationOther,
    LocationStatic,
    LocationTriangulation,
    Reserved58_5F,
    Mechanical = 0x60,
    MechanicalBooleanSwitch,
    MechanicalBooleanSwitchArray,
    MechanicalMultivalueSwitch,
    MechanicalForce,
    MechanicalPressure,
    MechanicalStrain,
    MechanicalWeight,
    MechanicalHapticVibrator,
    MechanicalHallEffectSwitch,
    Reserved6A_6F,
    Motion = 0x70,
    MotionAccelerometer1D,
    MotionAccelerometer2D,
    MotionAccelerometer3D,
    MotionGyrometer1D,
    MotionGyrometer2D,
    MotionGyrometer3D,
    MotionMotionDetector,
    MotionSpeedometer,
    MotionAccelerometer,
    MotionGyrometer,
    MotionGravityVector,
    MotionLinearAccelerometer,
    Reserved7D_7F,
    Orientation = 0x80,
    OrientationCompass1D,
    OrientationCompass2D,
    OrientationCompass3D,
    OrientationInclinometer1D,
    OrientationInclinometer2D,
    OrientationInclinometer3D,
    OrientationDistance1D,
    OrientationDistance2D,
    OrientationDistance3D,
    OrientationDeviceOrientation,
    OrientationCompass,
    OrientationInclinometer,
    OrientationDistance,
    OrientationRelativeOrientation,
    OrientationSimpleOrientation,
    Scanner,
    ScannerBarcode,
    ScannerRFID,
    ScannerNFC,
    Reserved94_9F,
    Time = 0xA0,
    TimeAlarmTimer,
    TimeRealTimeClock,
    ReservedA3_AF,
    PersonalActivity = 0xB0,
    PersonalActivityActivityDetection,
    PersonalActivityDevicePosition,
    PersonalActivityFloorTracker,
    PersonalActivityPedometer,
    PersonalActivityStepDetection,
    ReservedB6_BF,
    OrientationExtended = 0xC0,
    OrientationExtendedGeomagneticOrientation,
    OrientationExtendedMagnetometer,
    ReservedC3_CF,
    Gesture = 0xD0,
    GestureChassisFlipGesture,
    GestureHingeFoldGesture,
    ReservedD3_DF,
    Other = 0xE0,
    OtherCustom,
    OtherGeneric,
    OtherGenericEnumerator,
    OtherHingeAngle,
    ReservedE5_EF,
    VendorReserved1 = 0xF0,
    VendorReserved2,
    VendorReserved3,
    VendorReserved4,
    VendorReserved5,
    VendorReserved6,
    VendorReserved7,
    VendorReserved8,
    VendorReserved9,
    VendorReserved10,
    VendorReserved11,
    VendorReserved12,
    VendorReserved13,
    VendorReserved14,
    VendorReserved15,
    VendorReserved16,
    Reserved100_1FF,
    Event = 0x200,
    EventSensorState,
    EventSensorEvent,
    Reserved203_2FF,
    Property = 0x300,
    PropertyFriendlyName,
    PropertyPersistentUniqueID,
    PropertySensorStatus,
    PropertyMinimumReportInterval,
    PropertySensorManufacturer,
    PropertySensorModel,
    PropertySensorSerialNumber,
    PropertySensorDescription,
    PropertySensorConnectionType,
    PropertySensorDevicePath,
    PropertyHardwareRevision,
    PropertyFirmwareVersion,
    PropertyReleaseDate,
    PropertyReportInterval,
    PropertyChangeSensitivityAbsolute,
    PropertyChangeSensitivityPercentofRange,
    PropertyChangeSensitivityPercentRelative,
    PropertyAccuracy,
    PropertyResolution,
    PropertyMaximum,
    PropertyMinimum,
    PropertyReportingState,
    PropertySamplingRate,
    PropertyResponseCurve,
    PropertyPowerState,
    PropertyMaximumFIFOEvents,
    PropertyReportLatency,
    PropertyFlushFIFOEvents,
    PropertyMaximumPowerConsumption,
    PropertyIsPrimary,
    PropertyHumanPresenceDetectionType,
    Reserved320_3FF,
    DataFieldLocation = 0x400,
    Reserved401,
    DataFieldAltitudeAntennaSeaLevel,
    DataFieldDifferentialReferenceStationID,
    DataFieldAltitudeEllipsoidError,
    DataFieldAltitudeEllipsoid,
    DataFieldAltitudeSeaLevelError,
    DataFieldAltitudeSeaLevel,
    DataFieldDifferentialGPSDataAge,
    DataFieldErrorRadius,
    DataFieldFixQuality,
    DataFieldFixType,
    DataFieldGeoidalSeparation,
    DataFieldGPSOperationMode,
    DataFieldGPSSelectionMode,
    DataFieldGPSStatus,
    DataFieldPositionDilutionofPrecision,
    DataFieldHorizontalDilutionofPrecision,
    DataFieldVerticalDilutionofPrecision,
    DataFieldLatitude,
    DataFieldLongitude,
    DataFieldTRUEHeading,
    DataFieldMagneticHeading,
    DataFieldMagneticVariation,
    DataFieldSpeed,
    DataFieldSatellitesinView,
    DataFieldSatellitesinViewAzimuth,
    DataFieldSatellitesinViewElevation,
    DataFieldSatellitesinViewIDs,
    DataFieldSatellitesinViewPRNs,
    DataFieldSatellitesinViewS_NRatios,
    DataFieldSatellitesUsedCount,
    DataFieldSatellitesUsedPRNs,
    DataFieldNMEASentence,
    DataFieldAddressLine1,
    DataFieldAddressLine2,
    DataFieldCity,
    DataFieldStateorProvince,
    DataFieldCountryorRegion,
    DataFieldPostalCode,
    Reserved428_429,
    PropertyLocation,
    PropertyLocationDesiredAccuracy,
    Reserved42C_42F,
    DataFieldEnvironmental = 0x430,
    DataFieldAtmosphericPressure,
    Reserved432_432,
    DataFieldRelativeHumidity = 0x433,
    DataFieldTemperature,
    DataFieldWindDirection,
    DataFieldWindSpeed,
    DataFieldAirQualityIndex,
    DataFieldEquivalentCO2,
    DataFieldVolatileOrganicCompoundConcentration,
    DataFieldObjectPresence,
    DataFieldObjectProximityRange,
    DataFieldObjectProximityOutofRange,
    Reserved43D_43F,
    PropertyEnvironmental = 0x440,
    PropertyReferencePressure,
    Reserved442_44F,
    DataFieldMotion = 0x450,
    DataFieldMotionState,
    DataFieldAcceleration,
    DataFieldAccelerationAxisX,
    DataFieldAccelerationAxisY,
    DataFieldAccelerationAxisZ,
    DataFieldAngularVelocity,
    DataFieldAngularVelocityaboutXAxis,
    DataFieldAngularVelocityaboutYAxis,
    DataFieldAngularVelocityaboutZAxis,
    DataFieldAngularPosition,
    DataFieldAngularPositionaboutXAxis,
    DataFieldAngularPositionaboutYAxis,
    DataFieldAngularPositionaboutZAxis,
    DataFieldMotionSpeed,
    DataFieldMotionIntensity,
    Reserved460_46F,
    DataFieldOrientation = 0x470,
    DataFieldHeading,
    DataFieldHeadingXAxis,
    DataFieldHeadingYAxis,
    DataFieldHeadingZAxis,
    DataFieldHeadingCompensatedMagneticNorth,
    DataFieldHeadingCompensatedTRUENorth,
    DataFieldHeadingMagneticNorth,
    DataFieldHeadingTRUENorth,
    DataFieldDistance,
    DataFieldDistanceXAxis,
    DataFieldDistanceYAxis,
    DataFieldDistanceZAxis,
    DataFieldDistanceOut_of_Range,
    DataFieldTilt,
    DataFieldTiltXAxis,
    DataFieldTiltYAxis,
    DataFieldTiltZAxis,
    DataFieldRotationMatrix,
    DataFieldQuaternion,
    DataFieldMagneticFlux,
    DataFieldMagneticFluxXAxis,
    DataFieldMagneticFluxYAxis,
    DataFieldMagneticFluxZAxis,
    DataFieldMagnetometerAccuracy,
    DataFieldSimpleOrientationDirection,
    Reserved48A_48F,
    DataFieldMechanical = 0x490,
    DataFieldBooleanSwitchState,
    DataFieldBooleanSwitchArrayStates,
    DataFieldMultivalueSwitchValue,
    DataFieldForce,
    DataFieldAbsolutePressure,
    DataFieldGaugePressure,
    DataFieldStrain,
    DataFieldWeight,
    Reserved499_49F,
    PropertyMechanical = 0x4A0,
    PropertyVibrationState,
    PropertyForwardVibrationSpeed,
    PropertyBackwardVibrationSpeed,
    Reserved4A4_4AF,
    FieldBiometric = 0x4B0,
    DataFieldHumanPresence,
    DataFieldHumanProximityRange,
    DataFieldHumanProximityOutofRange,
    DataFieldHumanTouchState,
    DataFieldBloodPressure,
    DataFieldBloodPressureDiastolic,
    DataFieldBloodPressureSystolic,
    DataFieldHeartRate,
    DataFieldRestingHeartRate,
    DataFieldHeartbeatInterval,
    DataFieldRespiratoryRate,
    DataFieldSpO2,
    DataFieldHumanAttentionDetected,
    DataFieldHumanHeadAzimuth,
    DataFieldHumanHeadAltitude,
    DataFieldHumanHeadRoll,
    DataFieldHumanHeadPitch,
    DataFieldHumanHeadYaw,
    DataFieldHumanCorrelationId,
    Reserved4C4_4CF,
    DataFieldLight = 0x4D0,
    DataFieldIlluminance,
    DataFieldColorTemperature,
    DataFieldChromaticity,
    DataFieldChromaticityX,
    DataFieldChromaticityY,
    DataFieldConsumerIRSentenceReceive,
    DataFieldInfraredLight,
    DataFieldRedLight,
    DataFieldGreenLight,
    DataFieldBlueLight,
    DataFieldUltravioletALight,
    DataFieldUltravioletBLight,
    DataFieldUltravioletIndex,
    DataFieldNearInfraredLight,
    PropertyLight,
    PropertyConsumerIRSentenceSend,
    Reserved4E1_4E1,
    AutoBrightnessPreferred = 0x4E2,
    PropertyAutoColorPreferred,
    Reserved4E4_4EF,
    DataFieldScanner = 0x4F0,
    DataFieldRFIDTag40Bit,
    DataFieldNFCSentenceReceive,
    Reserved4F3_4F7,
    PropertyScanner = 0x4F8,
    PropertyNFCSentenceSend,
    Reserved4FA_4FF,
    DataFieldElectrical = 0x500,
    DataFieldCapacitance,
    DataFieldCurrent,
    DataFieldElectricalPower,
    DataFieldInductance,
    DataFieldResistance,
    DataFieldVoltage,
    DataFieldFrequency,
    DataFieldPeriod,
    DataFieldPercentofRange,
    Reserved50A_51F,
    DataFieldTime = 0x520,
    DataFieldYear,
    DataFieldMonth,
    DataFieldDay,
    DataFieldDayofWeek,
    DataFieldHour,
    DataFieldMinute,
    DataFieldSecond,
    DataFieldMillisecond,
    DataFieldTimestamp,
    DataFieldJulianDayofYear,
    DataFieldTimeSinceSystemBoot,
    Reserved52C_52F,
    PropertyTime = 0x530,
    PropertyTimeZoneOffsetfromUTC,
    PropertyTimeZoneName,
    PropertyDaylightSavingsTimeObserved,
    PropertyTimeTrimAdjustment,
    PropertyArmAlarm,
    Reserved536_53F,
    DataFieldCustom = 0x540,
    DataFieldCustomUsage,
    DataFieldCustomBooleanArray,
    DataFieldCustomValue,
    DataFieldCustomValue1,
    DataFieldCustomValue2,
    DataFieldCustomValue3,
    DataFieldCustomValue4,
    DataFieldCustomValue5,
    DataFieldCustomValue6,
    DataFieldCustomValue7,
    DataFieldCustomValue8,
    DataFieldCustomValue9,
    DataFieldCustomValue10,
    DataFieldCustomValue11,
    DataFieldCustomValue12,
    DataFieldCustomValue13,
    DataFieldCustomValue14,
    DataFieldCustomValue15,
    DataFieldCustomValue16,
    DataFieldCustomValue17,
    DataFieldCustomValue18,
    DataFieldCustomValue19,
    DataFieldCustomValue20,
    DataFieldCustomValue21,
    DataFieldCustomValue22,
    DataFieldCustomValue23,
    DataFieldCustomValue24,
    DataFieldCustomValue25,
    DataFieldCustomValue26,
    DataFieldCustomValue27,
    DataFieldCustomValue28,
    DataFieldGeneric,
    DataFieldGenericGUIDorPROPERTYKEY,
    DataFieldGenericCategoryGUID,
    DataFieldGenericTypeGUID,
    DataFieldGenericEventPROPERTYKEY,
    DataFieldGenericPropertyPROPERTYKEY,
    DataFieldGenericDataFieldPROPERTYKEY,
    DataFieldGenericEvent,
    DataFieldGenericProperty,
    DataFieldGenericDataField,
    DataFieldEnumeratorTableRowIndex,
    DataFieldEnumeratorTableRowCount,
    DataFieldGenericGUIDorPROPERTYKEYkind,
    DataFieldGenericGUID,
    DataFieldGenericPROPERTYKEY,
    DataFieldGenericTopLevelCollectionID,
    DataFieldGenericReportID,
    DataFieldGenericReportItemPositionIndex,
    DataFieldGenericFirmwareVARTYPE,
    DataFieldGenericUnitofMeasure,
    DataFieldGenericUnitExponent,
    DataFieldGenericReportSize,
    DataFieldGenericReportCount,
    Reserved577_57F,
    PropertyGeneric = 0x580,
    PropertyEnumeratorTableRowIndex,
    PropertyEnumeratorTableRowCount,
    Reserved583_58F,
    DataFieldPersonalActivity = 0x590,
    DataFieldActivityType,
    DataFieldActivityState,
    DataFieldDevicePosition,
    DataFieldStepCount,
    DataFieldStepCountReset,
    DataFieldStepDuration,
    DataFieldStepType,
    Reserved598_59F,
    PropertyMinimumActivityDetectionInterval = 0x5A0,
    PropertySupportedActivityTypes,
    PropertySubscribedActivityTypes,
    PropertySupportedStepTypes,
    PropertySubscribedStepTypes,
    PropertyFloorHeight,
    Reserved5A6_5AF,
    DataFieldCustomTypeID = 0x5B0,
    Reserved5B1_5BF,
    PropertyCustom = 0x5C0,
    PropertyCustomValue1,
    PropertyCustomValue2,
    PropertyCustomValue3,
    PropertyCustomValue4,
    PropertyCustomValue5,
    PropertyCustomValue6,
    PropertyCustomValue7,
    PropertyCustomValue8,
    PropertyCustomValue9,
    PropertyCustomValue10,
    PropertyCustomValue11,
    PropertyCustomValue12,
    PropertyCustomValue13,
    PropertyCustomValue14,
    PropertyCustomValue15,
    PropertyCustomValue16,
    Reserved5D1_5DF,
    DataFieldHinge = 0x5E0,
    DataFieldHingeAngle,
    Reserved5E2_5EF,
    DataFieldGestureSensor = 0x5F0,
    DataFieldGestureState,
    DataFieldHingeFoldInitialAngle,
    DataFieldHingeFoldFinalAngle,
    DataFieldHingeFoldContributingPanel,
    DataFieldHingeFoldType,
    Reserved5F6_7FF,
    SensorStateUndefined = 0x800,
    SensorStateReady,
    SensorStateNotAvailable,
    SensorStateNoData,
    SensorStateInitializing,
    SensorStateAccessDenied,
    SensorStateError,
    Reserved807_80F,
    SensorEventUnknown = 0x810,
    SensorEventStateChanged,
    SensorEventPropertyChanged,
    SensorEventDataUpdated,
    SensorEventPollResponse,
    SensorEventChangeSensitivity,
    SensorEventRangeMaximumReached,
    SensorEventRangeMinimumReached,
    SensorEventHighThresholdCrossUpward,
    SensorEventHighThresholdCrossDownward,
    SensorEventLowThresholdCrossUpward,
    SensorEventLowThresholdCrossDownward,
    SensorEventZeroThresholdCrossUpward,
    SensorEventZeroThresholdCrossDownward,
    SensorEventPeriodExceeded,
    SensorEventFrequencyExceeded,
    SensorEventComplexTrigger,
    Reserved821_82F,
    ConnectionTypePCIntegrated = 0x830,
    ConnectionTypePCAttached,
    ConnectionTypePCExternal,
    Reserved833_83F,
    ReportingStateReportNoEvents = 0x840,
    ReportingStateReportAllEvents,
    ReportingStateReportThresholdEvents,
    ReportingStateWakeOnNoEvents,
    ReportingStateWakeOnAllEvents,
    ReportingStateWakeOnThresholdEvents,
    ReportingStateAnytime,
    Reserved847_84F,
    PowerStateUndefined = 0x850,
    PowerStateD0FullPower,
    PowerStateD1LowPower,
    PowerStateD2StandbyPowerwithWakeup,
    PowerStateD3SleepwithWakeup,
    PowerStateD4PowerOff,
    Reserved856_85F,
    AccuracyDefault = 0x860,
    AccuracyHigh,
    AccuracyMedium,
    AccuracyLow,
    Reserved864_86F,
    FixQualityNoFix = 0x870,
    FixQualityGPS,
    FixQualityDGPS,
    Reserved873_87F,
    FixTypeNoFix = 0x880,
    FixTypeGPSSPSModeFixValid,
    FixTypeDGPSSPSModeFixValid,
    FixTypeGPSPPSModeFixValid,
    FixTypeRealTimeKinematic,
    FixTypeFloatRTK,
    FixTypeEstimated_deadreckoned,
    FixTypeManualInputMode,
    FixTypeSimulatorMode,
    Reserved889_88F,
    GPSOperationModeManual = 0x890,
    GPSOperationModeAutomatic,
    Reserved892_89F,
    GPSSelectionModeAutonomous = 0x8A0,
    GPSSelectionModeDGPS,
    GPSSelectionModeEstimated_deadreckoned,
    GPSSelectionModeManualInput,
    GPSSelectionModeSimulator,
    GPSSelectionModeDataNotValid,
    Reserved8A6_8AF,
    GPSStatusDataValid = 0x8B0,
    GPSStatusDataNotValid,
    Reserved8B2_8BF,
    DayofWeekSunday = 0x8C0,
    DayofWeekMonday,
    DayofWeekTuesday,
    DayofWeekWednesday,
    DayofWeekThursday,
    DayofWeekFriday,
    DayofWeekSaturday,
    Reserved8C7_8CF,
    KindCategory = 0x8D0,
    KindType,
    KindEvent,
    KindProperty,
    KindDataField,
    Reserved8D5_8DF,
    MagnetometerAccuracyLow = 0x8E0,
    MagnetometerAccuracyMedium,
    MagnetometerAccuracyHigh,
    Reserved8E3_8EF,
    SimpleOrientationDirectionNotRotated = 0x8F0,
    SimpleOrientationDirectionRotated90DegreesCCW,
    SimpleOrientationDirectionRotated180DegreesCCW,
    SimpleOrientationDirectionRotated270DegreesCCW,
    SimpleOrientationDirectionFaceUp,
    SimpleOrientationDirectionFaceDown,
    Reserved8F6_8FF,
    VT_NULL = 0x900,
    VT_BOOL,
    VT_UI1,
    VT_I1,
    VT_UI2,
    VT_I2,
    VT_UI4,
    VT_I4,
    VT_UI8,
    VT_I8,
    VT_R4,
    VT_R8,
    VT_WSTR,
    VT_STR,
    VT_CLSID,
    VT_VECTORVT_UI1,
    VT_F16E0,
    VT_F16E1,
    VT_F16E2,
    VT_F16E3,
    VT_F16E4,
    VT_F16E5,
    VT_F16E6,
    VT_F16E7,
    VT_F16E8,
    VT_F16E9,
    VT_F16EA,
    VT_F16EB,
    VT_F16EC,
    VT_F16ED,
    VT_F16EE,
    VT_F16EF,
    VT_F32E0,
    VT_F32E1,
    VT_F32E2,
    VT_F32E3,
    VT_F32E4,
    VT_F32E5,
    VT_F32E6,
    VT_F32E7,
    VT_F32E8,
    VT_F32E9,
    VT_F32EA,
    VT_F32EB,
    VT_F32EC,
    VT_F32ED,
    VT_F32EE,
    VT_F32EF,
    ActivityTypeUnknown,
    ActivityTypeStationary,
    ActivityTypeFidgeting,
    ActivityTypeWalking,
    ActivityTypeRunning,
    ActivityTypeInVehicle,
    ActivityTypeBiking,
    ActivityTypeIdle,
    Reserved938_93F,
    UnitNotSpecified = 0x940,
    UnitLux,
    UnitDegreesKelvin,
    UnitDegreesCelsius,
    UnitPascal,
    UnitNewton,
    UnitMeters_Second,
    UnitKilogram,
    UnitMeter,
    UnitMeters_Second_Second,
    UnitFarad,
    UnitAmpere,
    UnitWatt,
    UnitHenry,
    UnitOhm,
    UnitVolt,
    UnitHertz,
    UnitBar,
    UnitDegreesAnti_clockwise,
    UnitDegreesClockwise,
    UnitDegrees,
    UnitDegrees_Second,
    UnitDegrees_Second_Second,
    UnitKnot,
    UnitPercent,
    UnitSecond,
    UnitMillisecond,
    UnitG,
    UnitBytes,
    UnitMilligauss,
    UnitBits,
    Reserved95F_95F,
    ActivityStateNoStateChange = 0x960,
    ActivityStateStartActivity,
    ActivityStateEndActivity,
    Reserved963_96F,
    Exponent0 = 0x970,
    Exponent1,
    Exponent2,
    Exponent3,
    Exponent4,
    Exponent5,
    Exponent6,
    Exponent7,
    Exponent8,
    Exponent9,
    ExponentA,
    ExponentB,
    ExponentC,
    ExponentD,
    ExponentE,
    ExponentF,
    DevicePositionUnknown,
    DevicePositionUnchanged,
    DevicePositionOnDesk,
    DevicePositionInHand,
    DevicePositionMovinginBag,
    DevicePositionStationaryinBag,
    Reserved986_98F,
    StepTypeUnknown = 0x990,
    StepTypeWalking,
    StepTypeRunning,
    Reserved993_99F,
    GestureStateUnknown = 0x9A0,
    GestureStateStarted,
    GestureStateCompleted,
    GestureStateCancelled,
    Reserved9A4_9AF,
    HingeFoldContributingPanelUnknown = 0x9B0,
    HingeFoldContributingPanelPanel1,
    HingeFoldContributingPanelPanel2,
    HingeFoldContributingPanelBoth,
    HingeFoldTypeUnknown,
    HingeFoldTypeIncreasing,
    HingeFoldTypeDecreasing,
    Reserved9B7_9BF,
    HumanPresenceDetectionTypeVendor_DefinedNon_Biometric = 0x9C0,
    HumanPresenceDetectionTypeVendor_DefinedBiometric,
    HumanPresenceDetectionTypeFacialBiometric,
    HumanPresenceDetectionTypeAudioBiometric,
    Reserved9C4_FFF = 0x9C4,
    ModifierChangeSensitivityAbsolute = 0x1000,
    Reserved1001_10FF = 0x1001,
    ReservedforuseasChangeSensitivityAbsolutemodifierrange1100_17FF = 0x1100,
    Reserved1800_1FFF = 0x1800,
    ModifierMaximum =  0x2000,
    Reserved2001_20FF = 0x2001,
    ReservedforuseasMaximummodifierrange2100_27FF = 0x2100,
    Reserved2800_2FFF = 0x2800,
    ModifierMinimum = 0x3000,
    Reserved3001_30FF = 0x3001,
    ReservedforuseasMinimummodifierrange3100_37FF = 0x3100,
    Reserved3800_3FFF = 0x3800,
    ModifierAccuracy = 0x4000,
    Reserved4001_40FF = 0x4001,
    ReservedforuseasAccuracymodifierrange4100_47FF = 0x4100,
    Reserved4800_4FFF = 0x4800,
    ModifierResolution = 0x5000,
    Reserved5001_50FF = 0x5001,
    ReservedforuseasResolutionmodifierrange5100_57FF = 0x5100,
    Reserved5800_5FFF = 0x5800,
    ModifierThresholdHigh = 0x6000,
    Reserved6001_60FF = 0x6001,
    ReservedforuseasThresholdHighmodifierrange6100_67FF = 0x6100,
    Reserved6800_6FFF = 0x6800,
    ModifierThresholdLow = 0x7000,
    Reserved7001_70FF = 0x7001,
    ReservedforuseasThresholdLowmodifierrange7100_77FF = 0x7100,
    Reserved7800_7FFF = 0x7800,
    ModifierCalibrationOffset = 0x8000,
    Reserved8001_80FF = 0x8001,
    ReservedforuseasCalibrationOffsetmodifierrange8100_87FF = 0x8100,
    Reserved8800_8FFF = 0x8800,
    ModifierCalibrationMultiplier = 0x9000,
    Reserved9001_90FF = 0x9001,
    ReservedforuseasCalibrationMultipliermodifierrange9100_97FF = 0x9100,
    Reserved9800_9FFF = 0x9800,
    ModifierReportInterval = 0xA000,
    ReservedA001_A0FF = 0xA001,
    ReservedforuseasReportIntervalmodifierrangeA100_A7FF = 0xA100,
    ReservedA800_AFFF = 0xA800,
    ModifierFrequencyMax = 0xB000,
    ReservedB001_B0FF = 0xB001,
    ReservedforuseasFrequencyMaxmodifierrangeB100_B7FF = 0xB100,
    ReservedB800_BFFF = 0xB800,
    ModifierPeriodMax =    0xC000,
    ReservedC001_C0FF = 0xC001,
    ReservedforuseasPeriodMaxmodifierrangeC100_C7FF = 0xC100,
    ReservedC800_CFFF = 0xC800,
    ModifierChangeSensitivityPercentofRange = 0xD000,
    ReservedD001_D0FF = 0xD001,
    ReservedforuseasChangeSensitivityPercentmodifierrangeD100_D7FF = 0xD100,
    ReservedD800_DFFF = 0xD800,
    ModifierChangeSensitivityPercentRelative = 0xE000,
    ReservedE001_E0FF = 0xE001,
    ReservedforuseasChangeSensitivityPercentmodifierrangeE100_E7FF = 0xE100,
    ReservedE800_EFFF = 0xE800,
    ModifierVendorReserved = 0xF000,
    ReservedF001_F0FF,
    ReservedforuseasVendorReservedmodifierrangeF100_F7FF = 0xF100,
    ReservedF800_FFFF = 0xF800,
}
impl<T> From<T> for SensorUsage
where
    T: TryInto<u16>,
{
    fn from(value: T) -> Self {
        let value: u16 = value.try_into().unwrap_or(0);
        match value {
            0=> Self::Undefined,
            1=> Self::Sensor,
            2..16   => Self::Reserved02_0F,
                => Self::Biometric,
                => Self::BiometricHumanPresence,
                => Self::BiometricHumanProximity,
                => Self::BiometricHumanTouch,
                => Self::BiometricBloodPressure,
                => Self::BiometricBodyTemperature,
                => Self::BiometricHeartRate,
                => Self::BiometricHeartRateVariability,
                => Self::BiometricPeripheralOxygenSaturation,
                => Self::BiometricRespiratoryRate,
                => Self::Reserved1A_1F,
                => Self::Electrical,
                => Self::ElectricalCapacitance,
                => Self::ElectricalCurrent,
                => Self::ElectricalPower,
                => Self::ElectricalInductance,
                => Self::ElectricalResistance,
                => Self::ElectricalVoltage,
                => Self::ElectricalPotentiometer,
                => Self::ElectricalFrequency,
                => Self::ElectricalPeriod,
                => Self::Reserved2A_2F,
                => Self::Environmental,
                => Self::EnvironmentalAtmosphericPressure,
                => Self::EnvironmentalHumidity,
                => Self::EnvironmentalTemperature,
                => Self::EnvironmentalWindDirection,
                => Self::EnvironmentalWindSpeed,
                => Self::EnvironmentalAirQuality,
                => Self::EnvironmentalHeatIndex,
                => Self::EnvironmentalSurfaceTemperature,
                => Self::EnvironmentalVolatileOrganicCompounds,
                => Self::EnvironmentalObjectPresence,
                => Self::EnvironmentalObjectProximity,
                => Self::Reserved3C_3F,
                => Self::Light,
                => Self::LightAmbientLight,
                => Self::LightConsumerInfrared,
                => Self::LightInfraredLight,
                => Self::LightVisibleLight,
                => Self::LightUltravioletLight,
                => Self::Reserved46_4F,
                => Self::Location,
                => Self::LocationBroadcast,
                => Self::LocationDeadReckoning,
                => Self::LocationGPS_GlobalPositioningSystem,
                => Self::LocationLookup,
                => Self::LocationOther,
                => Self::LocationStatic,
                => Self::LocationTriangulation,
                => Self::Reserved58_5F,
                => Self::Mechanical,
                => Self::MechanicalBooleanSwitch,
                => Self::MechanicalBooleanSwitchArray,
                => Self::MechanicalMultivalueSwitch,
                => Self::MechanicalForce,
                => Self::MechanicalPressure,
                => Self::MechanicalStrain,
                => Self::MechanicalWeight,
                => Self::MechanicalHapticVibrator,
                => Self::MechanicalHallEffectSwitch,
                => Self::Reserved6A_6F,
                => Self::Motion,
                => Self::MotionAccelerometer1D,
                => Self::MotionAccelerometer2D,
                => Self::MotionAccelerometer3D,
                => Self::MotionGyrometer1D,
                => Self::MotionGyrometer2D,
                => Self::MotionGyrometer3D,
                => Self::MotionMotionDetector,
                => Self::MotionSpeedometer,
                => Self::MotionAccelerometer,
                => Self::MotionGyrometer,
                => Self::MotionGravityVector,
                => Self::MotionLinearAccelerometer,
                => Self::Reserved7D_7F,
                => Self::Orientation,
                => Self::OrientationCompass1D,
                => Self::OrientationCompass2D,
                => Self::OrientationCompass3D,
                => Self::OrientationInclinometer1D,
                => Self::OrientationInclinometer2D,
                => Self::OrientationInclinometer3D,
                => Self::OrientationDistance1D,
                => Self::OrientationDistance2D,
                => Self::OrientationDistance3D,
                => Self::OrientationDeviceOrientation,
                => Self::OrientationCompass,
                => Self::OrientationInclinometer,
                => Self::OrientationDistance,
                => Self::OrientationRelativeOrientation,
                => Self::OrientationSimpleOrientation,
                => Self::Scanner,
                => Self::ScannerBarcode,
                => Self::ScannerRFID,
                => Self::ScannerNFC,
                => Self::Reserved94_9F,
                => Self::Time,
                => Self::TimeAlarmTimer,
                => Self::TimeRealTimeClock,
                => Self::ReservedA3_AF,
                => Self::PersonalActivity,
                => Self::PersonalActivityActivityDetection,
                => Self::PersonalActivityDevicePosition,
                => Self::PersonalActivityFloorTracker,
                => Self::PersonalActivityPedometer,
                => Self::PersonalActivityStepDetection,
                => Self::ReservedB6_BF,
                => Self::OrientationExtended,
                => Self::OrientationExtendedGeomagneticOrientation,
                => Self::OrientationExtendedMagnetometer,
                => Self::ReservedC3_CF,
                => Self::Gesture,
                => Self::GestureChassisFlipGesture,
                => Self::GestureHingeFoldGesture,
                => Self::ReservedD3_DF,
                => Self::Other,
                => Self::OtherCustom,
                => Self::OtherGeneric,
                => Self::OtherGenericEnumerator,
                => Self::OtherHingeAngle,
                => Self::ReservedE5_EF,
                => Self::VendorReserved1,
                => Self::VendorReserved2,
                => Self::VendorReserved3,
                => Self::VendorReserved4,
                => Self::VendorReserved5,
                => Self::VendorReserved6,
                => Self::VendorReserved7,
                => Self::VendorReserved8,
                => Self::VendorReserved9,
                => Self::VendorReserved10,
                => Self::VendorReserved11,
                => Self::VendorReserved12,
                => Self::VendorReserved13,
                => Self::VendorReserved14,
                => Self::VendorReserved15,
                => Self::VendorReserved16,
                => Self::Reserved100_1FF,
                => Self::Event,
                => Self::EventSensorState,
                => Self::EventSensorEvent,
                => Self::Reserved203_2FF,
                => Self::Property,
                => Self::PropertyFriendlyName,
                => Self::PropertyPersistentUniqueID,
                => Self::PropertySensorStatus,
                => Self::PropertyMinimumReportInterval,
                => Self::PropertySensorManufacturer,
                => Self::PropertySensorModel,
                => Self::PropertySensorSerialNumber,
                => Self::PropertySensorDescription,
                => Self::PropertySensorConnectionType,
                => Self::PropertySensorDevicePath,
                => Self::PropertyHardwareRevision,
                => Self::PropertyFirmwareVersion,
                => Self::PropertyReleaseDate,
                => Self::PropertyReportInterval,
                => Self::PropertyChangeSensitivityAbsolute,
                => Self::PropertyChangeSensitivityPercentofRange,
                => Self::PropertyChangeSensitivityPercentRelative,
                => Self::PropertyAccuracy,
                => Self::PropertyResolution,
                => Self::PropertyMaximum,
                => Self::PropertyMinimum,
                => Self::PropertyReportingState,
                => Self::PropertySamplingRate,
                => Self::PropertyResponseCurve,
                => Self::PropertyPowerState,
                => Self::PropertyMaximumFIFOEvents,
                => Self::PropertyReportLatency,
                => Self::PropertyFlushFIFOEvents,
                => Self::PropertyMaximumPowerConsumption,
                => Self::PropertyIsPrimary,
                => Self::PropertyHumanPresenceDetectionType,
                => Self::Reserved320_3FF,
                => Self::DataFieldLocation,
                => Self::Reserved401,
                => Self::DataFieldAltitudeAntennaSeaLevel,
                => Self::DataFieldDifferentialReferenceStationID,
                => Self::DataFieldAltitudeEllipsoidError,
                => Self::DataFieldAltitudeEllipsoid,
                => Self::DataFieldAltitudeSeaLevelError,
                => Self::DataFieldAltitudeSeaLevel,
                => Self::DataFieldDifferentialGPSDataAge,
                => Self::DataFieldErrorRadius,
                => Self::DataFieldFixQuality,
                => Self::DataFieldFixType,
                => Self::DataFieldGeoidalSeparation,
                => Self::DataFieldGPSOperationMode,
                => Self::DataFieldGPSSelectionMode,
                => Self::DataFieldGPSStatus,
                => Self::DataFieldPositionDilutionofPrecision,
                => Self::DataFieldHorizontalDilutionofPrecision,
                => Self::DataFieldVerticalDilutionofPrecision,
                => Self::DataFieldLatitude,
                => Self::DataFieldLongitude,
                => Self::DataFieldTRUEHeading,
                => Self::DataFieldMagneticHeading,
                => Self::DataFieldMagneticVariation,
                => Self::DataFieldSpeed,
                => Self::DataFieldSatellitesinView,
                => Self::DataFieldSatellitesinViewAzimuth,
                => Self::DataFieldSatellitesinViewElevation,
                => Self::DataFieldSatellitesinViewIDs,
                => Self::DataFieldSatellitesinViewPRNs,
                => Self::DataFieldSatellitesinViewS_NRatios,
                => Self::DataFieldSatellitesUsedCount,
                => Self::DataFieldSatellitesUsedPRNs,
                => Self::DataFieldNMEASentence,
                => Self::DataFieldAddressLine1,
                => Self::DataFieldAddressLine2,
                => Self::DataFieldCity,
                => Self::DataFieldStateorProvince,
                => Self::DataFieldCountryorRegion,
                => Self::DataFieldPostalCode,
                => Self::Reserved428_429,
                => Self::PropertyLocation,
                => Self::PropertyLocationDesiredAccuracy,
                => Self::Reserved42C_42F,
                => Self::DataFieldEnvironmental,
                => Self::DataFieldAtmosphericPressure,
                => Self::Reserved432_432,
                => Self::DataFieldRelativeHumidity,
                => Self::DataFieldTemperature,
                => Self::DataFieldWindDirection,
                => Self::DataFieldWindSpeed,
                => Self::DataFieldAirQualityIndex,
                => Self::DataFieldEquivalentCO2,
                => Self::DataFieldVolatileOrganicCompoundConcentration,
                => Self::DataFieldObjectPresence,
                => Self::DataFieldObjectProximityRange,
                => Self::DataFieldObjectProximityOutofRange,
                => Self::Reserved43D_43F,
                => Self::PropertyEnvironmental,
                => Self::PropertyReferencePressure,
                => Self::Reserved442_44F,
                => Self::DataFieldMotion,
                => Self::DataFieldMotionState,
                => Self::DataFieldAcceleration,
                => Self::DataFieldAccelerationAxisX,
                => Self::DataFieldAccelerationAxisY,
                => Self::DataFieldAccelerationAxisZ,
                => Self::DataFieldAngularVelocity,
                => Self::DataFieldAngularVelocityaboutXAxis,
                => Self::DataFieldAngularVelocityaboutYAxis,
                => Self::DataFieldAngularVelocityaboutZAxis,
                => Self::DataFieldAngularPosition,
                => Self::DataFieldAngularPositionaboutXAxis,
                => Self::DataFieldAngularPositionaboutYAxis,
                => Self::DataFieldAngularPositionaboutZAxis,
                => Self::DataFieldMotionSpeed,
                => Self::DataFieldMotionIntensity,
                => Self::Reserved460_46F,
                => Self::DataFieldOrientation,
                => Self::DataFieldHeading,
                => Self::DataFieldHeadingXAxis,
                => Self::DataFieldHeadingYAxis,
                => Self::DataFieldHeadingZAxis,
                => Self::DataFieldHeadingCompensatedMagneticNorth,
                => Self::DataFieldHeadingCompensatedTRUENorth,
                => Self::DataFieldHeadingMagneticNorth,
                => Self::DataFieldHeadingTRUENorth,
                => Self::DataFieldDistance,
                => Self::DataFieldDistanceXAxis,
                => Self::DataFieldDistanceYAxis,
                => Self::DataFieldDistanceZAxis,
                => Self::DataFieldDistanceOut_of_Range,
                => Self::DataFieldTilt,
                => Self::DataFieldTiltXAxis,
                => Self::DataFieldTiltYAxis,
                => Self::DataFieldTiltZAxis,
                => Self::DataFieldRotationMatrix,
                => Self::DataFieldQuaternion,
                => Self::DataFieldMagneticFlux,
                => Self::DataFieldMagneticFluxXAxis,
                => Self::DataFieldMagneticFluxYAxis,
                => Self::DataFieldMagneticFluxZAxis,
                => Self::DataFieldMagnetometerAccuracy,
                => Self::DataFieldSimpleOrientationDirection,
                => Self::Reserved48A_48F,
                => Self::DataFieldMechanical,
                => Self::DataFieldBooleanSwitchState,
                => Self::DataFieldBooleanSwitchArrayStates,
                => Self::DataFieldMultivalueSwitchValue,
                => Self::DataFieldForce,
                => Self::DataFieldAbsolutePressure,
                => Self::DataFieldGaugePressure,
                => Self::DataFieldStrain,
                => Self::DataFieldWeight,
                => Self::Reserved499_49F,
                => Self::PropertyMechanical,
                => Self::PropertyVibrationState,
                => Self::PropertyForwardVibrationSpeed,
                => Self::PropertyBackwardVibrationSpeed,
                => Self::Reserved4A4_4AF,
                => Self::FieldBiometric,
                => Self::DataFieldHumanPresence,
                => Self::DataFieldHumanProximityRange,
                => Self::DataFieldHumanProximityOutofRange,
                => Self::DataFieldHumanTouchState,
                => Self::DataFieldBloodPressure,
                => Self::DataFieldBloodPressureDiastolic,
                => Self::DataFieldBloodPressureSystolic,
                => Self::DataFieldHeartRate,
                => Self::DataFieldRestingHeartRate,
                => Self::DataFieldHeartbeatInterval,
                => Self::DataFieldRespiratoryRate,
                => Self::DataFieldSpO2,
                => Self::DataFieldHumanAttentionDetected,
                => Self::DataFieldHumanHeadAzimuth,
                => Self::DataFieldHumanHeadAltitude,
                => Self::DataFieldHumanHeadRoll,
                => Self::DataFieldHumanHeadPitch,
                => Self::DataFieldHumanHeadYaw,
                => Self::DataFieldHumanCorrelationId,
                => Self::Reserved4C4_4CF,
                => Self::DataFieldLight,
                => Self::DataFieldIlluminance,
                => Self::DataFieldColorTemperature,
                => Self::DataFieldChromaticity,
                => Self::DataFieldChromaticityX,
                => Self::DataFieldChromaticityY,
                => Self::DataFieldConsumerIRSentenceReceive,
                => Self::DataFieldInfraredLight,
                => Self::DataFieldRedLight,
                => Self::DataFieldGreenLight,
                => Self::DataFieldBlueLight,
                => Self::DataFieldUltravioletALight,
                => Self::DataFieldUltravioletBLight,
                => Self::DataFieldUltravioletIndex,
                => Self::DataFieldNearInfraredLight,
                => Self::PropertyLight,
                => Self::PropertyConsumerIRSentenceSend,
                => Self::Reserved4E1_4E1,
                => Self::AutoBrightnessPreferred,
                => Self::PropertyAutoColorPreferred,
                => Self::Reserved4E4_4EF,
                => Self::DataFieldScanner,
                => Self::DataFieldRFIDTag40Bit,
                => Self::DataFieldNFCSentenceReceive,
                => Self::Reserved4F3_4F7,
                => Self::PropertyScanner,
                => Self::PropertyNFCSentenceSend,
                => Self::Reserved4FA_4FF,
                => Self::DataFieldElectrical,
                => Self::DataFieldCapacitance,
                => Self::DataFieldCurrent,
                => Self::DataFieldElectricalPower,
                => Self::DataFieldInductance,
                => Self::DataFieldResistance,
                => Self::DataFieldVoltage,
                => Self::DataFieldFrequency,
                => Self::DataFieldPeriod,
                => Self::DataFieldPercentofRange,
                => Self::Reserved50A_51F,
                => Self::DataFieldTime,
                => Self::DataFieldYear,
                => Self::DataFieldMonth,
                => Self::DataFieldDay,
                => Self::DataFieldDayofWeek,
                => Self::DataFieldHour,
                => Self::DataFieldMinute,
                => Self::DataFieldSecond,
                => Self::DataFieldMillisecond,
                => Self::DataFieldTimestamp,
                => Self::DataFieldJulianDayofYear,
                => Self::DataFieldTimeSinceSystemBoot,
                => Self::Reserved52C_52F,
                => Self::PropertyTime,
                => Self::PropertyTimeZoneOffsetfromUTC,
                => Self::PropertyTimeZoneName,
                => Self::PropertyDaylightSavingsTimeObserved,
                => Self::PropertyTimeTrimAdjustment,
                => Self::PropertyArmAlarm,
                => Self::Reserved536_53F,
                => Self::DataFieldCustom,
                => Self::DataFieldCustomUsage,
                => Self::DataFieldCustomBooleanArray,
                => Self::DataFieldCustomValue,
                => Self::DataFieldCustomValue1,
                => Self::DataFieldCustomValue2,
                => Self::DataFieldCustomValue3,
                => Self::DataFieldCustomValue4,
                => Self::DataFieldCustomValue5,
                => Self::DataFieldCustomValue6,
                => Self::DataFieldCustomValue7,
                => Self::DataFieldCustomValue8,
                => Self::DataFieldCustomValue9,
                => Self::DataFieldCustomValue10,
                => Self::DataFieldCustomValue11,
                => Self::DataFieldCustomValue12,
                => Self::DataFieldCustomValue13,
                => Self::DataFieldCustomValue14,
                => Self::DataFieldCustomValue15,
                => Self::DataFieldCustomValue16,
                => Self::DataFieldCustomValue17,
                => Self::DataFieldCustomValue18,
                => Self::DataFieldCustomValue19,
                => Self::DataFieldCustomValue20,
                => Self::DataFieldCustomValue21,
                => Self::DataFieldCustomValue22,
                => Self::DataFieldCustomValue23,
                => Self::DataFieldCustomValue24,
                => Self::DataFieldCustomValue25,
                => Self::DataFieldCustomValue26,
                => Self::DataFieldCustomValue27,
                => Self::DataFieldCustomValue28,
                => Self::DataFieldGeneric,
                => Self::DataFieldGenericGUIDorPROPERTYKEY,
                => Self::DataFieldGenericCategoryGUID,
                => Self::DataFieldGenericTypeGUID,
                => Self::DataFieldGenericEventPROPERTYKEY,
                => Self::DataFieldGenericPropertyPROPERTYKEY,
                => Self::DataFieldGenericDataFieldPROPERTYKEY,
                => Self::DataFieldGenericEvent,
                => Self::DataFieldGenericProperty,
                => Self::DataFieldGenericDataField,
                => Self::DataFieldEnumeratorTableRowIndex,
                => Self::DataFieldEnumeratorTableRowCount,
                => Self::DataFieldGenericGUIDorPROPERTYKEYkind,
                => Self::DataFieldGenericGUID,
                => Self::DataFieldGenericPROPERTYKEY,
                => Self::DataFieldGenericTopLevelCollectionID,
                => Self::DataFieldGenericReportID,
                => Self::DataFieldGenericReportItemPositionIndex,
                => Self::DataFieldGenericFirmwareVARTYPE,
                => Self::DataFieldGenericUnitofMeasure,
                => Self::DataFieldGenericUnitExponent,
                => Self::DataFieldGenericReportSize,
                => Self::DataFieldGenericReportCount,
                => Self::Reserved577_57F,
                => Self::PropertyGeneric,
                => Self::PropertyEnumeratorTableRowIndex,
                => Self::PropertyEnumeratorTableRowCount,
                => Self::Reserved583_58F,
                => Self::DataFieldPersonalActivity,
                => Self::DataFieldActivityType,
                => Self::DataFieldActivityState,
                => Self::DataFieldDevicePosition,
                => Self::DataFieldStepCount,
                => Self::DataFieldStepCountReset,
                => Self::DataFieldStepDuration,
                => Self::DataFieldStepType,
                => Self::Reserved598_59F,
                => Self::PropertyMinimumActivityDetectionInterval,
                => Self::PropertySupportedActivityTypes,
                => Self::PropertySubscribedActivityTypes,
                => Self::PropertySupportedStepTypes,
                => Self::PropertySubscribedStepTypes,
                => Self::PropertyFloorHeight,
                => Self::Reserved5A6_5AF,
                => Self::DataFieldCustomTypeID,
                => Self::Reserved5B1_5BF,
                => Self::PropertyCustom,
                => Self::PropertyCustomValue1,
                => Self::PropertyCustomValue2,
                => Self::PropertyCustomValue3,
                => Self::PropertyCustomValue4,
                => Self::PropertyCustomValue5,
                => Self::PropertyCustomValue6,
                => Self::PropertyCustomValue7,
                => Self::PropertyCustomValue8,
                => Self::PropertyCustomValue9,
                => Self::PropertyCustomValue10,
                => Self::PropertyCustomValue11,
                => Self::PropertyCustomValue12,
                => Self::PropertyCustomValue13,
                => Self::PropertyCustomValue14,
                => Self::PropertyCustomValue15,
                => Self::PropertyCustomValue16,
                => Self::Reserved5D1_5DF,
                => Self::DataFieldHinge,
                => Self::DataFieldHingeAngle,
                => Self::Reserved5E2_5EF,
                => Self::DataFieldGestureSensor,
                => Self::DataFieldGestureState,
                => Self::DataFieldHingeFoldInitialAngle,
                => Self::DataFieldHingeFoldFinalAngle,
                => Self::DataFieldHingeFoldContributingPanel,
                => Self::DataFieldHingeFoldType,
                => Self::Reserved5F6_7FF,
                => Self::SensorStateUndefined,
                => Self::SensorStateReady,
                => Self::SensorStateNotAvailable,
                => Self::SensorStateNoData,
                => Self::SensorStateInitializing,
                => Self::SensorStateAccessDenied,
                => Self::SensorStateError,
                => Self::Reserved807_80F,
                => Self::SensorEventUnknown,
                => Self::SensorEventStateChanged,
                => Self::SensorEventPropertyChanged,
                => Self::SensorEventDataUpdated,
                => Self::SensorEventPollResponse,
                => Self::SensorEventChangeSensitivity,
                => Self::SensorEventRangeMaximumReached,
                => Self::SensorEventRangeMinimumReached,
                => Self::SensorEventHighThresholdCrossUpward,
                => Self::SensorEventHighThresholdCrossDownward,
                => Self::SensorEventLowThresholdCrossUpward,
                => Self::SensorEventLowThresholdCrossDownward,
                => Self::SensorEventZeroThresholdCrossUpward,
                => Self::SensorEventZeroThresholdCrossDownward,
                => Self::SensorEventPeriodExceeded,
                => Self::SensorEventFrequencyExceeded,
                => Self::SensorEventComplexTrigger,
                => Self::Reserved821_82F,
                => Self::ConnectionTypePCIntegrated,
                => Self::ConnectionTypePCAttached,
                => Self::ConnectionTypePCExternal,
                => Self::Reserved833_83F,
                => Self::ReportingStateReportNoEvents,
                => Self::ReportingStateReportAllEvents,
                => Self::ReportingStateReportThresholdEvents,
                => Self::ReportingStateWakeOnNoEvents,
                => Self::ReportingStateWakeOnAllEvents,
                => Self::ReportingStateWakeOnThresholdEvents,
                => Self::ReportingStateAnytime,
                => Self::Reserved847_84F,
                => Self::PowerStateUndefined,
                => Self::PowerStateD0FullPower,
                => Self::PowerStateD1LowPower,
                => Self::PowerStateD2StandbyPowerwithWakeup,
                => Self::PowerStateD3SleepwithWakeup,
                => Self::PowerStateD4PowerOff,
                => Self::Reserved856_85F,
                => Self::AccuracyDefault,
                => Self::AccuracyHigh,
                => Self::AccuracyMedium,
                => Self::AccuracyLow,
                => Self::Reserved864_86F,
                => Self::FixQualityNoFix,
                => Self::FixQualityGPS,
                => Self::FixQualityDGPS,
                => Self::Reserved873_87F,
                => Self::FixTypeNoFix,
                => Self::FixTypeGPSSPSModeFixValid,
                => Self::FixTypeDGPSSPSModeFixValid,
                => Self::FixTypeGPSPPSModeFixValid,
                => Self::FixTypeRealTimeKinematic,
                => Self::FixTypeFloatRTK,
                => Self::FixTypeEstimated_deadreckoned,
                => Self::FixTypeManualInputMode,
                => Self::FixTypeSimulatorMode,
                => Self::Reserved889_88F,
                => Self::GPSOperationModeManual,
                => Self::GPSOperationModeAutomatic,
                => Self::Reserved892_89F,
                => Self::GPSSelectionModeAutonomous,
                => Self::GPSSelectionModeDGPS,
                => Self::GPSSelectionModeEstimated_deadreckoned,
                => Self::GPSSelectionModeManualInput,
                => Self::GPSSelectionModeSimulator,
                => Self::GPSSelectionModeDataNotValid,
                => Self::Reserved8A6_8AF,
                => Self::GPSStatusDataValid,
                => Self::GPSStatusDataNotValid,
                => Self::Reserved8B2_8BF,
                => Self::DayofWeekSunday,
                => Self::DayofWeekMonday,
                => Self::DayofWeekTuesday,
                => Self::DayofWeekWednesday,
                => Self::DayofWeekThursday,
                => Self::DayofWeekFriday,
                => Self::DayofWeekSaturday,
                => Self::Reserved8C7_8CF,
                => Self::KindCategory,
                => Self::KindType,
                => Self::KindEvent,
                => Self::KindProperty,
                => Self::KindDataField,
                => Self::Reserved8D5_8DF,
                => Self::MagnetometerAccuracyLow,
                => Self::MagnetometerAccuracyMedium,
                => Self::MagnetometerAccuracyHigh,
                => Self::Reserved8E3_8EF,
                => Self::SimpleOrientationDirectionNotRotated,
                => Self::SimpleOrientationDirectionRotated90DegreesCCW,
                => Self::SimpleOrientationDirectionRotated180DegreesCCW,
                => Self::SimpleOrientationDirectionRotated270DegreesCCW,
                => Self::SimpleOrientationDirectionFaceUp,
                => Self::SimpleOrientationDirectionFaceDown,
                => Self::Reserved8F6_8FF,
                => Self::VT_NULL,
                => Self::VT_BOOL,
                => Self::VT_UI1,
                => Self::VT_I1,
                => Self::VT_UI2,
                => Self::VT_I2,
                => Self::VT_UI4,
                => Self::VT_I4,
                => Self::VT_UI8,
                => Self::VT_I8,
                => Self::VT_R4,
                => Self::VT_R8,
                => Self::VT_WSTR,
                => Self::VT_STR,
                => Self::VT_CLSID,
                => Self::VT_VECTORVT_UI1,
                => Self::VT_F16E0,
                => Self::VT_F16E1,
                => Self::VT_F16E2,
                => Self::VT_F16E3,
                => Self::VT_F16E4,
                => Self::VT_F16E5,
                => Self::VT_F16E6,
                => Self::VT_F16E7,
                => Self::VT_F16E8,
                => Self::VT_F16E9,
                => Self::VT_F16EA,
                => Self::VT_F16EB,
                => Self::VT_F16EC,
                => Self::VT_F16ED,
                => Self::VT_F16EE,
                => Self::VT_F16EF,
                => Self::VT_F32E0,
                => Self::VT_F32E1,
                => Self::VT_F32E2,
                => Self::VT_F32E3,
                => Self::VT_F32E4,
                => Self::VT_F32E5,
                => Self::VT_F32E6,
                => Self::VT_F32E7,
                => Self::VT_F32E8,
                => Self::VT_F32E9,
                => Self::VT_F32EA,
                => Self::VT_F32EB,
                => Self::VT_F32EC,
                => Self::VT_F32ED,
                => Self::VT_F32EE,
                => Self::VT_F32EF,
                => Self::ActivityTypeUnknown,
                => Self::ActivityTypeStationary,
                => Self::ActivityTypeFidgeting,
                => Self::ActivityTypeWalking,
                => Self::ActivityTypeRunning,
                => Self::ActivityTypeInVehicle,
                => Self::ActivityTypeBiking,
                => Self::ActivityTypeIdle,
                => Self::Reserved938_93F,
                => Self::UnitNotSpecified,
                => Self::UnitLux,
                => Self::UnitDegreesKelvin,
                => Self::UnitDegreesCelsius,
                => Self::UnitPascal,
                => Self::UnitNewton,
                => Self::UnitMeters_Second,
                => Self::UnitKilogram,
                => Self::UnitMeter,
                => Self::UnitMeters_Second_Second,
                => Self::UnitFarad,
                => Self::UnitAmpere,
                => Self::UnitWatt,
                => Self::UnitHenry,
                => Self::UnitOhm,
                => Self::UnitVolt,
                => Self::UnitHertz,
                => Self::UnitBar,
                => Self::UnitDegreesAnti_clockwise,
                => Self::UnitDegreesClockwise,
                => Self::UnitDegrees,
                => Self::UnitDegrees_Second,
                => Self::UnitDegrees_Second_Second,
                => Self::UnitKnot,
                => Self::UnitPercent,
                => Self::UnitSecond,
                => Self::UnitMillisecond,
                => Self::UnitG,
                => Self::UnitBytes,
                => Self::UnitMilligauss,
                => Self::UnitBits,
                => Self::Reserved95F_95F,
                => Self::ActivityStateNoStateChange,
                => Self::ActivityStateStartActivity,
                => Self::ActivityStateEndActivity,
                => Self::Reserved963_96F,
                => Self::Exponent0,
                => Self::Exponent1,
                => Self::Exponent2,
                => Self::Exponent3,
                => Self::Exponent4,
                => Self::Exponent5,
                => Self::Exponent6,
                => Self::Exponent7,
                => Self::Exponent8,
                => Self::Exponent9,
                => Self::ExponentA,
                => Self::ExponentB,
                => Self::ExponentC,
                => Self::ExponentD,
                => Self::ExponentE,
                => Self::ExponentF,
                => Self::DevicePositionUnknown,
                => Self::DevicePositionUnchanged,
                => Self::DevicePositionOnDesk,
                => Self::DevicePositionInHand,
                => Self::DevicePositionMovinginBag,
                => Self::DevicePositionStationaryinBag,
                => Self::Reserved986_98F,
                => Self::StepTypeUnknown,
                => Self::StepTypeWalking,
                => Self::StepTypeRunning,
                => Self::Reserved993_99F,
                => Self::GestureStateUnknown,
                => Self::GestureStateStarted,
                => Self::GestureStateCompleted,
                => Self::GestureStateCancelled,
                => Self::Reserved9A4_9AF,
                => Self::HingeFoldContributingPanelUnknown,
                => Self::HingeFoldContributingPanelPanel1,
                => Self::HingeFoldContributingPanelPanel2,
                => Self::HingeFoldContributingPanelBoth,
                => Self::HingeFoldTypeUnknown,
                => Self::HingeFoldTypeIncreasing,
                => Self::HingeFoldTypeDecreasing,
                => Self::Reserved9B7_9BF,
                => Self::HumanPresenceDetectionTypeVendor_DefinedNon_Biometric,
                => Self::HumanPresenceDetectionTypeVendor_DefinedBiometric,
                => Self::HumanPresenceDetectionTypeFacialBiometric,
                => Self::HumanPresenceDetectionTypeAudioBiometric,
                => Self::Reserved9C4_FFF,
                => Self::ModifierChangeSensitivityAbsolute,
                => Self::Reserved1001_10FF,
                => Self::ReservedforuseasChangeSensitivityAbsolutemodifierrange1100_17FF,
                => Self::Reserved1800_1FFF,
                => Self::ModifierMaximum,
                => Self::Reserved2001_20FF,
                => Self::ReservedforuseasMaximummodifierrange2100_27FF,
                => Self::Reserved2800_2FFF,
                => Self::ModifierMinimum,
                => Self::Reserved3001_30FF,
                => Self::ReservedforuseasMinimummodifierrange3100_37FF,
                => Self::Reserved3800_3FFF,
                => Self::ModifierAccuracy,
                => Self::Reserved4001_40FF,
                => Self::ReservedforuseasAccuracymodifierrange4100_47FF,
                => Self::Reserved4800_4FFF,
                => Self::ModifierResolution,
                => Self::Reserved5001_50FF,
                => Self::ReservedforuseasResolutionmodifierrange5100_57FF,
                => Self::Reserved5800_5FFF,
                => Self::ModifierThresholdHigh,
                => Self::Reserved6001_60FF,
                => Self::ReservedforuseasThresholdHighmodifierrange6100_67FF,
                => Self::Reserved6800_6FFF,
                => Self::ModifierThresholdLow,
                => Self::Reserved7001_70FF,
                => Self::ReservedforuseasThresholdLowmodifierrange7100_77FF,
                => Self::Reserved7800_7FFF,
                => Self::ModifierCalibrationOffset,
                => Self::Reserved8001_80FF,
                => Self::ReservedforuseasCalibrationOffsetmodifierrange8100_87FF,
                => Self::Reserved8800_8FFF,
                => Self::ModifierCalibrationMultiplier,
                => Self::Reserved9001_90FF,
                => Self::ReservedforuseasCalibrationMultipliermodifierrange9100_97FF,
                => Self::Reserved9800_9FFF,
                => Self::ModifierReportInterval,
                => Self::ReservedA001_A0FF,
                => Self::ReservedforuseasReportIntervalmodifierrangeA100_A7FF,
                => Self::ReservedA800_AFFF,
                => Self::ModifierFrequencyMax,
                => Self::ReservedB001_B0FF,
                => Self::ReservedforuseasFrequencyMaxmodifierrange,
                => Self::ReservedB800_BFFF,
                => Self::ModifierPeriodMax,
                => Self::ReservedC001_C0FF,
                => Self::ReservedforuseasPeriodMaxmodifierrange,
                => Self::ReservedC800_CFFF,
                => Self::ModifierChangeSensitivityPercentofRange,
                => Self::ReservedD001_D0FF,
                => Self::ReservedforuseasChangeSensitivityPercentmodifierrange,
                => Self::ReservedD800_DFFF,
                => Self::ModifierChangeSensitivityPercentRelative,
                => Self::ReservedE001_E0FF,
                => Self::ReservedforuseasChangeSensitivityPercentmodifierrangeE100_E7FF,
                => Self::ReservedE800_EFFF,
                => Self::ModifierVendorReserved = 0xF000,
            => Self::ReservedF001_F0FF,
            => Self::ReservedforuseasVendorReservedmodifierrangeF100_F7FF,
            => Self::ReservedF800_FFFF,
        }
    }
}
