#[non_exhaustive]
#[derive(Clone, Copy, PartialEq, PartialOrd, Ord, Eq, Hash, Debug, Default)]
#[repr(u16)]
pub enum BrailleDisplayUsage {
    #[default]
    Undefined,
    BrailleDisplay,
    BrailleRow,
    _8DotBrailleCell,
    _6DotBrailleCell,
    NumberofBrailleCells,
    ScreenReaderControl,
    ScreenReaderIdentifier,
    Reserved08_F9(u16),
    RouterSet1 = 250,
    RouterSet2,
    RouterSet3,
    ReservedFD_FF(u16),
    RouterKey = 256,
    RowRouterKey,
    Reserved102_1FF(u16),
    BrailleButtons = 512,
    BrailleKeyboardDot1,
    BrailleKeyboardDot2,
    BrailleKeyboardDot3,
    BrailleKeyboardDot4,
    BrailleKeyboardDot5,
    BrailleKeyboardDot6,
    BrailleKeyboardDot7,
    BrailleKeyboardDot8,
    BrailleKeyboardSpace,
    BrailleKeyboardLeftSpace,
    BrailleKeyboardRightSpace,
    BrailleFaceControls,
    BrailleLeftControls,
    BrailleRightControls,
    BrailleTopControls,
    BrailleJoystickCenter,
    BrailleJoystickUp,
    BrailleJoystickDown,
    BrailleJoystickLeft,
    BrailleJoystickRight,
    BrailleD_PadCenter,
    BrailleD_PadUp,
    BrailleD_PadDown,
    BrailleD_PadLeft,
    BrailleD_PadRight,
    BraillePanLeft,
    BraillePanRight,
    BrailleRockerUp,
    BrailleRockerDown,
    BrailleRockerPress,
    Reserved21F_FFFF(u16),
}
impl<T> From<T> for BrailleDisplayUsage
where
    T: TryInto<u16>,
{
    fn from(value: T) -> Self {
        let value: u16 = value.try_into().unwrap_or(0);

        match value {
            0 => Self::Undefined,
            1 => Self::BrailleDisplay,
            2 => Self::BrailleRow,
            3 => Self::_8DotBrailleCell,
            4 => Self::_6DotBrailleCell,
            5 => Self::NumberofBrailleCells,
            6 => Self::ScreenReaderControl,
            7 => Self::ScreenReaderIdentifier,
            8..250 => Self::Reserved08_F9(value),
            250 => Self::RouterSet1,
            251 => Self::RouterSet2,
            252 => Self::RouterSet3,
            253..256 => Self::ReservedFD_FF(value),
            256 => Self::RouterKey,
            257 => Self::RowRouterKey,
            258..512 => Self::Reserved102_1FF(value),
            512 => Self::BrailleButtons,
            513 => Self::BrailleKeyboardDot1,
            514 => Self::BrailleKeyboardDot2,
            515 => Self::BrailleKeyboardDot3,
            516 => Self::BrailleKeyboardDot4,
            517 => Self::BrailleKeyboardDot5,
            518 => Self::BrailleKeyboardDot6,
            519 => Self::BrailleKeyboardDot7,
            520 => Self::BrailleKeyboardDot8,
            521 => Self::BrailleKeyboardSpace,
            522 => Self::BrailleKeyboardLeftSpace,
            523 => Self::BrailleKeyboardRightSpace,
            524 => Self::BrailleFaceControls,
            525 => Self::BrailleLeftControls,
            526 => Self::BrailleRightControls,
            527 => Self::BrailleTopControls,
            528 => Self::BrailleJoystickCenter,
            529 => Self::BrailleJoystickUp,
            530 => Self::BrailleJoystickDown,
            531 => Self::BrailleJoystickLeft,
            532 => Self::BrailleJoystickRight,
            533 => Self::BrailleD_PadCenter,
            534 => Self::BrailleD_PadUp,
            535 => Self::BrailleD_PadDown,
            536 => Self::BrailleD_PadLeft,
            537 => Self::BrailleD_PadRight,
            538 => Self::BraillePanLeft,
            539 => Self::BraillePanRight,
            540 => Self::BrailleRockerUp,
            541 => Self::BrailleRockerDown,
            542 => Self::BrailleRockerPress,
            543..=65535 => Self::Reserved21F_FFFF(value),
        }
    }
}
