#[derive(Clone, Copy, PartialEq, PartialOrd, Ord, Eq, Hash, Debug, Default)]
#[non_exhaustive]
#[repr(u16)]
pub enum GameControlsUsage {
    #[default]
    Undefined,
    _3DGameController,
    PinballDevice,
    GunDevice,
    Reserved04_1F(u16),
    PointofView = 32,
    TurnRight_Left,
    PitchForward_Backward,
    RollRight_Left,
    MoveRight_Left,
    MoveForward_Backward,
    MoveUp_Down,
    LeanRight_Left,
    LeanForward_Backward,
    HeightofPOV,
    Flipper,
    SecondaryFlipper,
    Bump,
    NewGame,
    ShootBall,
    Player,
    GunBolt,
    GunClip,
    GunSelector,
    GunSingleShot,
    GunBurst,
    GunAutomatic,
    GunSafety,
    GamepadFire_Jump,
    Reserved38,
    GamepadTrigger,
    Form_fittingGamepad,
    Reserved3B_FFFF(u16),
}
impl<T> From<T> for GameControlsUsage
where
    T: TryInto<u16>,
{
    fn from(value: T) -> Self {
        let value = value.try_into().unwrap_or(0);
        match value {
            0 => Self::Undefined,
            1 => Self::_3DGameController,
            2 => Self::PinballDevice,
            3 => Self::GunDevice,
            4..32 => Self::Reserved04_1F(value),
            32 => Self::PointofView,
            33 => Self::TurnRight_Left,
            34 => Self::PitchForward_Backward,
            35 => Self::RollRight_Left,
            36 => Self::MoveRight_Left,
            37 => Self::MoveForward_Backward,
            38 => Self::MoveUp_Down,
            39 => Self::LeanRight_Left,
            40 => Self::LeanForward_Backward,
            41 => Self::HeightofPOV,
            42 => Self::Flipper,
            43 => Self::SecondaryFlipper,
            44 => Self::Bump,
            45 => Self::NewGame,
            46 => Self::ShootBall,
            47 => Self::Player,
            48 => Self::GunBolt,
            49 => Self::GunClip,
            50 => Self::GunSelector,
            51 => Self::GunSingleShot,
            52 => Self::GunBurst,
            53 => Self::GunAutomatic,
            54 => Self::GunSafety,
            55 => Self::GamepadFire_Jump,
            56 => Self::Reserved38,
            57 => Self::GamepadTrigger,
            58 => Self::Form_fittingGamepad,
            59..=65535 => Self::Reserved3B_FFFF(value),
        }
    }
}
