name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install libpcap
        run: sudo apt-get install -y libpcap-dev
      - name: update Rust toolchain
        run: rustup update
      - name: update crates
        run: cargo update
      - name: Install Dependencies
        run: cargo fetch
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
